// frameworks/registry.mjs
// =============================================================================
// THE FRAMEWORK REGISTRY - single source of truth for every evaluated thinking
// method (shipped or not). The catalog (docs/internal/research/framework-catalog.md),
// the advisor's recommendable set, and (later, SP4) the public Framework Library
// are GENERATED and drift-checked from this file. Edit entries here; never hand-edit
// the generated views.
//
// FORMAT: a zero-dependency ES data module (not YAML) - the repo's scripts are
// strictly zero-dep and Node has no built-in YAML parser. A .mjs object literal keeps
// the YAML ergonomics the spec wanted (inline comments, multi-line reasoning, no
// quote-escaping, trailing commas, diff-friendly) while staying parser-free: every
// consumer (gen-registry.mjs, check-registry.mjs, the Astro site) is Node and imports
// it directly. The contract is frameworks/registry.schema.json; scripts/check-registry.mjs
// enforces it. This file must contain ONLY data (an exported object literal), no logic.
//
// FAMILY NOTE: `family` uses the 11-family CATALOG (universe) taxonomy, which differs
// by design from the live skill metadata.family slugs (a separate, coarser grouping the
// 34 shipped skills + the Astro families/ pages use). The registry must cover all 102
// methods, most of which are unbuilt and have no skill metadata; harmonizing the two
// taxonomies is a noted follow-up, out of scope for SP3.
//
// SEED: migrated 2026-06-03 from the truthed-up framework-catalog.md (113 table rows ->
// 102 distinct methods: 10 expansion re-listings deduped into their families,
// decision-journal de-duplicated across families 7 and 11). 34 are shipped skills.
// =============================================================================

export default {
  version: 1,
  seededDate: '2026-06-03',

  // Ordered catalog families (slug -> display/prose name used in the generated catalog).
  families: [
    { slug: 'perspective-shifting-and-multi-lens', name: 'Perspective-shifting and multi-lens' },
    { slug: 'divergent-ideation-and-idea-expansion', name: 'Divergent ideation and idea expansion' },
    { slug: 'problem-framing-and-reframing', name: 'Problem framing and reframing' },
    { slug: 'assumption-and-belief-challenge', name: 'Assumption and belief challenge' },
    { slug: 'risk-failure-and-resilience', name: 'Risk, failure, and resilience' },
    { slug: 'systems-and-consequences', name: 'Systems and consequences' },
    { slug: 'decision-and-option-evaluation', name: 'Decision and option evaluation' },
    { slug: 'strategy-and-opportunity', name: 'Strategy and opportunity' },
    { slug: 'synthesis-and-reasoning-clarity', name: 'Synthesis and reasoning clarity' },
    { slug: 'facilitation-and-group-structures', name: 'Facilitation and group structures' },
    { slug: 'meta-thinking-and-reflection', name: 'Meta-thinking and reflection' },
  ],

  frameworks: [
    // -------------------------------------------------------------------------
    // 1. Perspective-shifting and multi-lens
    // -------------------------------------------------------------------------
    {
      slug: 'parallel-perspectives-review',
      name: 'Parallel Perspectives Review',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'examine a decision through separated lenses (facts/upside/risk/intuition/alternatives/process)',
      reasoning: 'The de-branded parallel-thinking mechanism; absorbs the Six Thinking Hats and stakeholder-lens moves.',
      evalCases: 'skills/think-parallel-perspectives-review/eval/cases.md',
      aliases: ['parallel-thinking', 'separated-lens review'],
    },
    {
      slug: 'red-team-light',
      name: 'Red Team / Blue Team',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'construct the strongest adversarial case against a thesis',
      reasoning: 'Shipped as red-team-light; absorbs steelmanning as its core move.',
      evalCases: 'skills/think-red-team-light/eval/cases.md',
      aliases: ['Red Team', 'Blue Team'],
    },
    {
      slug: 'stakeholder-lens-review',
      name: 'Stakeholder Lens Review',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'parallel-perspectives-review',
      oneLine: "walk a proposal through each affected party's eyes",
      reasoning: 'Subsumed: ships as the stakeholder mode of parallel-perspectives.',
    },
    {
      slug: 'steelmanning',
      name: 'Steelmanning',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'red-team-light',
      oneLine: 'state the strongest version of an opposing view before responding',
      reasoning: 'Subsumed: it is the core move of red-team-light.',
    },
    {
      slug: 'six-thinking-hats',
      name: 'Six Thinking Hats',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'X',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'branded parallel-thinking ritual',
      reasoning: 'IP gate opened (SP9): re-tagged on evidence + distinctness alone. The mechanism already ships descriptively as parallel-perspectives-review; branded evidence is weak (X). Documented, not shipped; include only with the trademark + weak-evidence caveat.',
      branded: true,
      attribution: 'Edward de Bono, 1985',
      trademark: 'Six Thinking Hats (de Bono method; "Six Thinking Hats" is a trademark of the de Bono estate / IP holders)',
      aliases: ['6 Thinking Hats', 'de Bono hats'],
    },
    {
      slug: 'role-storming',
      name: 'Role-storming',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'generate ideas while adopting another identity',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
    },
    {
      slug: 'outside-in-inside-out-framing',
      name: 'Outside-in / Inside-out framing',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'alternate market view and capability view',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Outside-in framing', 'Inside-out framing'],
    },
    {
      slug: 'disney-creative-strategy',
      name: 'Disney Creative Strategy',
      family: 'perspective-shifting-and-multi-lens',
      tier: 'A',
      status: 'excl',
      verdict: 'reject',
      oneLine: 'dreamer/realist/critic cycle',
      reasoning: 'Redundant with parallel-perspectives; anecdotal evidence. Documented for completeness.',
      branded: true,
      attribution: 'Robert Dilts (NLP modeling of Walt Disney)',
      trademark: 'Disney Method (Dilts); "Disney" is a trademark of The Walt Disney Company',
      aliases: ['Disney Method', 'Walt Disney Strategy'],
    },

    // -------------------------------------------------------------------------
    // 2. Divergent ideation and idea expansion
    // -------------------------------------------------------------------------
    {
      slug: 'brainwriting',
      name: 'Brainwriting 6-3-5 / NGT',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'silent parallel written generation + build-on',
      reasoning: 'S-tier empirical-core member. Absorbs silent-writing-before-discussion and the timeboxed Crazy-8s mode.',
      evalCases: 'skills/think-brainwriting/eval/cases.md',
      aliases: ['Brainwriting 6-3-5', '6-3-5', 'NGT', 'Nominal Group Technique'],
    },
    {
      slug: 'far-analogy-ideation',
      name: 'Far-analogy ideation',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'transfer deep structure from distant domains',
      reasoning: 'S-tier empirical-core member. Absorbs forced-connections / random-stimulus.',
      evalCases: 'skills/think-far-analogy-ideation/eval/cases.md',
      aliases: ['Far analogy', 'analogical ideation'],
    },
    {
      slug: 'scamper',
      name: 'SCAMPER',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'seven transformation prompts on a seed idea',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-scamper/eval/cases.md',
      aliases: ['Substitute Combine Adapt Modify Put-to-other-use Eliminate Reverse'],
    },
    {
      slug: 'question-burst',
      name: 'Question Burst',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'rapid questions-only burst, then rank + pick',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-question-burst/eval/cases.md',
      attribution: 'Hal Gregersen (Question Burst)',
    },
    {
      slug: 'assumption-reversal',
      name: 'Assumption Reversal',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'negate foundational premises to generate options',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-assumption-reversal/eval/cases.md',
    },
    {
      slug: 'morphological-analysis',
      name: 'Morphological analysis',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'enumerate the solution space by parameter combination',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      attribution: 'Fritz Zwicky (morphological analysis)',
      aliases: ['Morphological box', 'Zwicky box'],
    },
    {
      slug: 'worst-possible-idea',
      name: 'Worst possible idea / reverse brainstorming',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'generate bad ideas, then invert',
      reasoning: 'Candidate; relates to inversion.',
      aliases: ['reverse brainstorming'],
    },
    {
      slug: 'crazy-8s',
      name: 'Crazy 8s',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'brainwriting',
      oneLine: 'eight sketches in eight minutes',
      reasoning: 'Subsumed: a timeboxed mode of brainwriting (the timeboxed-generation mechanism).',
      aliases: ['Crazy Eights'],
    },
    {
      slug: 'lotus-blossom',
      name: 'Lotus Blossom',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'expand a center into 8 sub-themes, recurse',
      reasoning: 'Candidate; spatial, markdown-limited.',
      aliases: ['Lotus Blossom Technique', 'MY method'],
    },
    {
      slug: 'forced-connections',
      name: 'Forced connections / Random stimulus',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'far-analogy-ideation',
      oneLine: 'pair the problem with an unrelated stimulus',
      reasoning: 'Subsumed as a thinking method: a single unrelated stimulus is a mode of far-analogy ideation. This fold is about the single-stimulus METHOD; it is distinct from the think-random-frameworks meta-skill (an applicator that draws whole frameworks at random and applies each), which imports complete analytical apparatuses rather than injecting one provocation.',
      aliases: ['Random stimulus', 'Random entry'],
    },
    {
      slug: 'alternate-uses-constraint-insertion-removal',
      name: 'Alternate uses / Constraint insertion-removal',
      family: 'divergent-ideation-and-idea-expansion',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'loosen functional fixedness; add/strip a constraint',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Alternate uses', 'Constraint insertion', 'Constraint removal'],
    },

    // -------------------------------------------------------------------------
    // 3. Problem framing and reframing
    // -------------------------------------------------------------------------
    {
      slug: 'problem-restatement',
      name: 'Problem Restatement',
      family: 'problem-framing-and-reframing',
      tier: 'M',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'rewrite the problem several ways, pick a better frame',
      reasoning: 'Built and validated. Absorbs How-Might-We, Is/Is-Not, and Frame-storming.',
      evalCases: 'skills/think-problem-restatement/eval/cases.md',
      aliases: ['Problem reframing'],
    },
    {
      slug: 'abstraction-laddering',
      name: 'Abstraction Laddering',
      family: 'problem-framing-and-reframing',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'move up (why) and down (how) to the right altitude',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-abstraction-laddering/eval/cases.md',
      aliases: ['Abstraction ladder', 'Why-How ladder'],
    },
    {
      slug: 'first-principles',
      name: 'First Principles Thinking',
      family: 'problem-framing-and-reframing',
      tier: 'P',
      status: 'recipe',
      verdict: 'recipe',
      oneLine: 'decompose to fundamental truths, reason up',
      reasoning: 'Ships as the first-principles recipe (chains abstraction-laddering + assumption-reversal); no separable standalone mechanism.',
      aliases: ['First principles', 'First-principles reasoning'],
    },
    {
      slug: 'how-might-we',
      name: 'How Might We',
      family: 'problem-framing-and-reframing',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'problem-restatement',
      oneLine: 'turn an insight into an opportunity question',
      reasoning: 'Subsumed: an output of problem-restatement.',
      aliases: ['HMW'],
    },
    {
      slug: 'is-is-not-analysis',
      name: 'Is / Is Not analysis',
      family: 'problem-framing-and-reframing',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'problem-restatement',
      oneLine: 'sharpen scope by what the problem is and is not',
      reasoning: 'Subsumed: a problem-restatement move.',
      aliases: ['Is/Is-Not'],
    },
    {
      slug: 'frame-storming',
      name: 'Frame storming',
      family: 'problem-framing-and-reframing',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'problem-restatement',
      oneLine: 'brainstorm the framing, not the solution',
      reasoning: 'Subsumed: problem-restatement.',
      aliases: ['Framestorming'],
    },
    {
      slug: 'five-whys',
      name: 'Five Whys',
      family: 'problem-framing-and-reframing',
      tier: 'X',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'iterative why to trace a cause',
      reasoning: 'Flag: reliable only for simple linear failures (Card 2017); misleading beyond them. Fishbone/Ishikawa is the recommended multi-cause upgrade.',
      attribution: 'Sakichi Toyoda / Toyota Production System',
      aliases: ['5 Whys'],
    },

    // -------------------------------------------------------------------------
    // 4. Assumption and belief challenge
    // -------------------------------------------------------------------------
    {
      slug: 'argument-mapping',
      name: 'Argument Mapping',
      family: 'assumption-and-belief-challenge',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'diagram claim, reasons, co-premises, objections',
      reasoning: 'S-tier empirical-core member.',
      evalCases: 'skills/think-argument-mapping/eval/cases.md',
      aliases: ['Argument map'],
    },
    {
      slug: 'authentic-dissent',
      name: 'Authentic Dissent',
      family: 'assumption-and-belief-challenge',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'engineer for genuine minority dissent (not role-played)',
      reasoning: 'S-tier empirical-core member. Absorbs the intent of Devil’s Advocacy, which underperforms role-played.',
      evalCases: 'skills/think-authentic-dissent/eval/cases.md',
      attribution: 'Charlan Nemeth (authentic vs contrived dissent)',
    },
    {
      slug: 'natural-frequency-bayesian',
      name: 'Natural-frequency Bayesian framing',
      family: 'assumption-and-belief-challenge',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 're-express conditional probabilities as frequencies',
      reasoning: 'S-tier empirical-core member.',
      evalCases: 'skills/think-natural-frequency-bayesian/eval/cases.md',
      attribution: 'Gerd Gigerenzer (natural frequencies)',
      aliases: ['Natural frequencies', 'frequency framing'],
    },
    {
      slug: 'evidence-vs-inference-sort',
      name: 'Evidence vs Inference Sort',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'label claims evidence / inference / assumption',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-evidence-vs-inference-sort/eval/cases.md',
    },
    {
      slug: 'ladder-of-inference-check',
      name: 'Ladder of Inference Check',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'reconstruct the climb from data to conclusion',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-ladder-of-inference-check/eval/cases.md',
      attribution: 'Chris Argyris / Peter Senge (Ladder of Inference)',
      aliases: ['Ladder of Inference'],
    },
    {
      slug: 'what-would-have-to-be-true',
      name: 'What Would Have to Be True',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'turn a claim into testable conditions',
      reasoning: 'Built and validated. Absorbs Key Assumptions Check and Double-crux, both of which reduce to its killer/testable conditions.',
      evalCases: 'skills/think-what-would-have-to-be-true/eval/cases.md',
      attribution: 'Roger Martin (what would have to be true)',
      aliases: ['WWHTBT'],
    },
    {
      slug: 'key-assumptions-check',
      name: 'Key Assumptions Check / Assumption Mapping',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'excl',
      verdict: 'reject',
      oneLine: "inventory and rank a plan's assumptions",
      reasoning: 'Rejected 2026-06-03: same assumption-ledger as what-would-have-to-be-true (was briefly proposed [next]).',
      aliases: ['Assumption Mapping', 'KAC'],
    },
    {
      slug: 'cognitive-bias-checklist',
      name: 'Cognitive bias checklist',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'run a decision against relevant biases',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
    },
    {
      slug: 'inversion',
      name: 'Inversion',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'ask how to guarantee failure, then avoid it',
      reasoning: 'Candidate; overlaps assumption-reversal + premortem.',
    },
    {
      slug: 'counterfactual-reasoning',
      name: 'Counterfactual reasoning',
      family: 'assumption-and-belief-challenge',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: "examine 'what if X had been different'",
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
    },
    {
      slug: 'devils-advocacy',
      name: "Devil's Advocacy",
      family: 'assumption-and-belief-challenge',
      tier: 'X',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'assign someone to argue against',
      reasoning: 'Flag: role-played dissent underperforms genuine minority dissent (Nemeth); shipped intent via authentic-dissent.',
      attribution: 'Charlan Nemeth (critique of contrived dissent)',
      aliases: ["Devil's Advocate"],
    },
    {
      slug: 'double-crux',
      name: 'Double-crux',
      family: 'assumption-and-belief-challenge',
      tier: 'C',
      status: 'excl',
      verdict: 'reject',
      oneLine: 'find the single belief whose change would flip each side of a disagreement',
      reasoning: 'Rejected 2026-06-03: solo-reduces to what-would-have-to-be-true’s killer conditions.',
      attribution: 'CFAR (Center for Applied Rationality)',
      aliases: ['Double crux'],
    },

    // -------------------------------------------------------------------------
    // 5. Risk, failure, and resilience
    // -------------------------------------------------------------------------
    {
      slug: 'premortem',
      name: 'Premortem',
      family: 'risk-failure-and-resilience',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'imagine the plan failed, work back to causes',
      reasoning: 'Empirical-core member. Absorbs Kill-criteria / Tripwires into its register.',
      evalCases: 'skills/think-premortem/eval/cases.md',
      attribution: 'Gary Klein (premortem)',
      aliases: ['Pre-mortem', 'prospective hindsight'],
    },
    {
      slug: 'reference-class-forecasting',
      name: 'Reference Class Forecasting',
      family: 'risk-failure-and-resilience',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'anchor an estimate on the base rate of comparable cases',
      reasoning: 'S-tier empirical-core member.',
      evalCases: 'skills/think-reference-class-forecasting/eval/cases.md',
      attribution: 'Kahneman & Tversky; Flyvbjerg (reference class forecasting)',
      aliases: ['RCF', 'outside view'],
    },
    {
      slug: 'woop',
      name: 'WOOP / MCII',
      family: 'risk-failure-and-resilience',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'wish-outcome-obstacle-plan with an if-then',
      reasoning: 'S-tier empirical-core member.',
      evalCases: 'skills/think-woop/eval/cases.md',
      attribution: 'Gabriele Oettingen (WOOP / Mental Contrasting with Implementation Intentions)',
      aliases: ['WOOP', 'MCII', 'Mental Contrasting'],
    },
    {
      slug: 'backcasting',
      name: 'Backcasting',
      family: 'risk-failure-and-resilience',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'from a desired future, work back to the path',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-backcasting/eval/cases.md',
    },
    {
      slug: 'fmea-lite',
      name: 'FMEA-lite',
      family: 'risk-failure-and-resilience',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'list failure modes by likelihood x severity x detection',
      reasoning: 'Candidate; overlaps premortem.',
      attribution: 'Failure Mode and Effects Analysis (US military / aerospace origin)',
      aliases: ['FMEA', 'Failure Mode and Effects Analysis'],
    },
    {
      slug: 'kill-criteria-tripwires',
      name: 'Kill criteria / Tripwires',
      family: 'risk-failure-and-resilience',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'premortem',
      oneLine: 'pre-decided stop signals and conditions',
      reasoning: "Subsumed: inside premortem's register.",
      aliases: ['Kill criteria', 'Tripwires'],
    },
    {
      slug: 'regret-minimization',
      name: 'Regret minimization',
      family: 'risk-failure-and-resilience',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'choose the least-future-regret option',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      attribution: 'Jeff Bezos popularized (regret minimization framework)',
    },
    {
      slug: 'pre-commitment-ulysses-contract',
      name: 'Pre-commitment / Ulysses contract',
      family: 'risk-failure-and-resilience',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'bind future behavior in advance against known weakness',
      reasoning: 'Candidate; complements WOOP and premortem tripwires.',
      aliases: ['Ulysses contract', 'Ulysses pact', 'pre-commitment'],
    },

    // -------------------------------------------------------------------------
    // 6. Systems and consequences
    // -------------------------------------------------------------------------
    {
      slug: 'futures-wheel',
      name: 'Futures Wheel',
      family: 'systems-and-consequences',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'map first/second/third-order consequences outward',
      reasoning: 'Built and validated. Absorbs Second-Order Effects.',
      evalCases: 'skills/think-futures-wheel/eval/cases.md',
      attribution: 'Jerome Glenn (Futures Wheel)',
    },
    {
      slug: 'iceberg-model',
      name: 'Iceberg Model',
      family: 'systems-and-consequences',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'events -> patterns -> structures -> mental models',
      reasoning: 'Built and validated. Owns the leverage-points fold (Meadows leverage-ladder mode) and cites its Meadows source.',
      evalCases: 'skills/think-iceberg-model/eval/cases.md',
      aliases: ['Iceberg of systems thinking'],
    },
    {
      slug: 'stocks-and-flows-reasoning',
      name: 'Stocks and Flows reasoning',
      family: 'systems-and-consequences',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'reason about accumulations and rates',
      reasoning: 'S-tier empirical-core member (Sterman); one of the last two core stragglers, now shipped.',
      evalCases: 'skills/think-stocks-and-flows-reasoning/eval/cases.md',
      attribution: 'John Sterman (system dynamics)',
      aliases: ['Stocks and flows', 'stock-and-flow'],
    },
    {
      slug: 'causal-loop-diagrams',
      name: 'Causal Loop Diagrams',
      family: 'systems-and-consequences',
      tier: 'M',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'diagram reinforcing/balancing feedback loops',
      reasoning: 'Built and validated.',
      evalCases: 'skills/think-causal-loop-diagrams/eval/cases.md',
      aliases: ['CLD', 'Causal loop diagram'],
    },
    {
      slug: 'second-order-effects',
      name: 'Second-Order Effects',
      family: 'systems-and-consequences',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'futures-wheel',
      oneLine: "lightweight 'and then what?' prompt",
      reasoning: 'Subsumed: a mode of futures-wheel.',
      aliases: ['Second-order thinking'],
    },
    {
      slug: 'leverage-points',
      name: 'Systems map / Leverage points',
      family: 'systems-and-consequences',
      tier: 'C',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'iceberg-model',
      oneLine: 'sketch elements/relationships; find intervention points',
      reasoning: 'Re-vetted 2026-06-03: [cand] -> [fold]. Owned by iceberg-model (Meadows leverage-ladder mode), which already cites its Meadows source.',
      attribution: 'Donella Meadows, 1999 (Leverage Points)',
      aliases: ['Systems map', 'Leverage points', 'Meadows leverage points'],
    },
    {
      slug: 'three-horizons',
      name: 'Three Horizons',
      family: 'systems-and-consequences',
      tier: 'C',
      status: 'cand',
      verdict: 'build',
      oneLine: 'present / transition / emerging future',
      reasoning: 'Candidate (foresight).',
      attribution: 'Baghai/Coley/White (McKinsey); Bill Sharpe (Three Horizons)',
      aliases: ['3 Horizons'],
    },
    {
      slug: 'causal-layered-analysis',
      name: 'Causal Layered Analysis',
      family: 'systems-and-consequences',
      tier: 'C',
      status: 'cand',
      verdict: 'build',
      oneLine: 'litany / system / worldview / myth layers',
      reasoning: 'Candidate (foresight).',
      attribution: 'Sohail Inayatullah (Causal Layered Analysis)',
      aliases: ['CLA'],
    },
    {
      slug: 'theory-of-constraints',
      name: 'Theory of Constraints',
      family: 'systems-and-consequences',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'find and exploit the system bottleneck',
      reasoning: 'Candidate; a distinct systems-intervention lens (find the binding bottleneck and exploit/elevate it).',
      attribution: 'Eliyahu Goldratt (Theory of Constraints / The Goal)',
      aliases: ['TOC', 'bottleneck analysis'],
    },
    {
      slug: 'fishbone-ishikawa',
      name: 'Fishbone / Ishikawa',
      family: 'systems-and-consequences',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'structured multi-cause diagram',
      reasoning: 'Candidate; the recommended multi-cause upgrade to Five-Whys.',
      attribution: 'Kaoru Ishikawa (Ishikawa/fishbone diagram)',
      aliases: ['Ishikawa diagram', 'Cause-and-effect diagram', 'Fishbone diagram'],
    },

    // -------------------------------------------------------------------------
    // 7. Decision and option evaluation
    // -------------------------------------------------------------------------
    {
      slug: 'decision-option-review',
      name: 'Decision Option Review',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'compare options against weighted criteria',
      reasoning: 'Built and validated. Absorbs Multi-Criteria Decision Analysis.',
      evalCases: 'skills/think-decision-option-review/eval/cases.md',
      aliases: ['Weighted decision matrix'],
    },
    {
      slug: 'one-way-vs-two-way-door',
      name: 'One-way vs Two-way Door',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'classify by reversibility, match deliberation',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-one-way-vs-two-way-door/eval/cases.md',
      attribution: 'Jeff Bezos popularized (one-way / two-way doors)',
      aliases: ['Reversibility test', 'Type 1 / Type 2 decisions'],
    },
    {
      slug: 'decision-journal',
      name: 'Decision Journal',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'record decision + expectation + confidence for calibration',
      reasoning: 'Built and validated. Spans decision evaluation and meta-thinking-and-reflection; one registry entry, primary family decision-and-option-evaluation.',
      evalCases: 'skills/think-decision-journal/eval/cases.md',
      aliases: ['Decision diary'],
    },
    {
      slug: 'multi-criteria-decision-analysis',
      name: 'Multi-Criteria Decision Analysis',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'decision-option-review',
      oneLine: 'weighted scoring across criteria',
      reasoning: 'Subsumed: equivalent to decision-option-review.',
      aliases: ['MCDA'],
    },
    {
      slug: 'decision-brief-pr-faq',
      name: 'Decision Brief / PR-FAQ',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'force a decision into a short structured memo',
      reasoning: 'Candidate; overlaps pyramid-principle.',
      attribution: 'Amazon (PR-FAQ / working-backwards)',
      aliases: ['PR-FAQ', 'Decision memo'],
    },
    {
      slug: 'pairwise-comparison',
      name: 'Pairwise comparison',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'compare two at a time to rank fuzzy criteria',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Paired comparison'],
    },
    {
      slug: 'expected-value-decision-tree',
      name: 'Expected-value / decision-tree',
      family: 'decision-and-option-evaluation',
      tier: 'M',
      status: 'cand',
      verdict: 'build',
      oneLine: 'weigh outcomes by probability x magnitude',
      reasoning: 'Candidate; the quantitative complement to decision-option-review.',
      aliases: ['Expected value', 'Decision tree', 'EV'],
    },
    {
      slug: 'minimax-regret',
      name: 'Minimax regret',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'minimize worst-case regret',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Savage minimax regret'],
    },
    {
      slug: 'fermi-estimation',
      name: 'Fermi estimation',
      family: 'decision-and-option-evaluation',
      tier: 'M',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'structured order-of-magnitude estimate from decomposition',
      reasoning: 'Built and validated as think-fermi-estimation.',
      evalCases: 'skills/think-fermi-estimation/eval/cases.md',
      attribution: 'Enrico Fermi (Fermi problems)',
      aliases: ['Fermi problem', 'order-of-magnitude estimation'],
    },
    {
      slug: 'eisenhower-moscow-pareto',
      name: 'Eisenhower / MoSCoW / Pareto',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'urgent-important triage; vital-few focus',
      reasoning: 'Candidate; simple, high-frequency prioritization (could be one skill).',
      attribution: 'Eisenhower matrix; Pareto (80/20); MoSCoW (DSDM)',
      aliases: ['Eisenhower matrix', 'MoSCoW', 'Pareto', '80/20'],
    },
    {
      slug: 'kepner-tregoe',
      name: 'Kepner-Tregoe',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'structured situation / problem / decision / potential-problem analysis',
      reasoning: 'Candidate; comprehensive but heavy. Documented with attribution; ships only if it clears evidence + distinctness.',
      branded: true,
      attribution: 'Charles Kepner & Benjamin Tregoe',
      trademark: 'Kepner-Tregoe (registered trademark of Kepner-Tregoe, Inc.)',
      aliases: ['KT analysis', 'K-T'],
    },
    {
      slug: 'cynefin',
      name: 'Cynefin',
      family: 'decision-and-option-evaluation',
      tier: 'C',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'sort clear / complicated / complex / chaotic',
      reasoning: 'IP gate opened (SP9): re-tagged on evidence + distinctness. Cargo-cult risk and under-tested (C); documented with attribution, not shipped. Include only with the trademark caveat.',
      branded: true,
      attribution: 'Dave Snowden (Cynefin framework)',
      trademark: 'Cynefin (The Cynefin Co. / formerly Cognitive Edge)',
      aliases: ['Cynefin framework'],
    },
    {
      slug: 'ice-rice-wsjf',
      name: 'ICE / RICE / WSJF',
      family: 'decision-and-option-evaluation',
      tier: 'V',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'prioritization scores',
      reasoning: 'Flag: false-precision warning (vendor scoring). Include only with the false-precision caveat.',
      branded: true,
      attribution: 'RICE (Intercom); WSJF (Scaled Agile / SAFe); ICE (Sean Ellis)',
      trademark: 'SAFe and WSJF are trademarks of Scaled Agile, Inc.; RICE originates at Intercom',
      aliases: ['ICE', 'RICE', 'WSJF'],
    },
    {
      slug: 'ooda-loop',
      name: 'OODA Loop',
      family: 'decision-and-option-evaluation',
      tier: 'P',
      status: 'excl',
      verdict: 'reject',
      oneLine: 'observe-orient-decide-act',
      reasoning: 'Excluded: more useful as agent loop architecture than as a user skill.',
      attribution: 'John Boyd (OODA loop)',
      aliases: ['OODA'],
    },
    {
      slug: 'linear-model-aggregation',
      name: 'Mechanical / linear-model aggregation',
      family: 'decision-and-option-evaluation',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'combine cues with a simple fixed formula instead of holistic judgment',
      reasoning: 'S-tier empirical-core member (Meehl/Dawes); one of the last two core stragglers, now shipped as think-linear-model-aggregation.',
      evalCases: 'skills/think-linear-model-aggregation/eval/cases.md',
      attribution: 'Paul Meehl; Robyn Dawes (improper linear models)',
      aliases: ['Linear model aggregation', 'Mechanical aggregation', 'improper linear models', "Dawes' rule"],
    },

    // -------------------------------------------------------------------------
    // 8. Strategy and opportunity (weakest cross-domain fit; many defer to pm-skills)
    // -------------------------------------------------------------------------
    {
      slug: 'opportunity-solution-tree',
      name: 'Opportunity-Solution Tree',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'pm',
      verdict: 'reject',
      oneLine: 'outcome -> opportunities -> solutions',
      reasoning: 'Defer to pm-skills (product discovery).',
      attribution: 'Teresa Torres (Opportunity Solution Tree)',
      aliases: ['OST'],
    },
    {
      slug: 'value-proposition-contrast',
      name: 'Value proposition contrast',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'pm',
      verdict: 'reject',
      oneLine: 'sharpen vs the next-best alternative',
      reasoning: 'Defer to pm-skills (PM / business-domain).',
      aliases: ['Value-prop contrast'],
    },
    {
      slug: 'white-space-adjacent-possible',
      name: 'White-space / adjacent-possible / 10x-vs-incremental',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'locate uncontested or reachable opportunity',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['White-space analysis', 'adjacent possible', '10x vs incremental'],
    },
    {
      slug: 'moat-defensibility-lens',
      name: 'Moat / defensibility lens',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'test what stops a competitor copying you',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Moat analysis', 'Defensibility'],
    },
    {
      slug: 'scenario-planning',
      name: 'Scenario planning',
      family: 'strategy-and-opportunity',
      tier: 'M',
      status: 'cand',
      verdict: 'build',
      oneLine: 'construct multiple plausible futures (2x2)',
      reasoning: 'Candidate; distinct from futures-wheel (consequences) and backcasting (path); evidence thin.',
      attribution: 'Pierre Wack / Royal Dutch Shell (scenario planning)',
      aliases: ['Scenario analysis', '2x2 scenarios'],
    },
    {
      slug: 'pestle',
      name: 'PEST(LE)',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'scan macro-environmental forces',
      reasoning: 'Candidate; macro complement (political/economic/social/technological/legal/environmental); partly pm.',
      aliases: ['PEST', 'PESTLE', 'PESTEL'],
    },
    {
      slug: 'jobs-to-be-done',
      name: 'Jobs To Be Done',
      family: 'strategy-and-opportunity',
      tier: 'P',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'frame demand as progress sought',
      reasoning: 'Flag: multi-school ambiguity; also a pm-domain method. Include only with the ambiguity caveat.',
      attribution: 'Clayton Christensen / Tony Ulwick (Jobs To Be Done)',
      aliases: ['JTBD'],
    },
    {
      slug: 'wardley-mapping',
      name: 'Wardley Mapping',
      family: 'strategy-and-opportunity',
      tier: 'C',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'value chain vs evolution',
      reasoning: 'IP gate opened (SP9): re-tagged on evidence + distinctness. Cargo-cult risk and under-tested (C); documented with attribution, not shipped. Include only with the license + caveat.',
      branded: true,
      attribution: 'Simon Wardley (Wardley Mapping)',
      trademark: 'Wardley Mapping (licensed CC BY-SA 4.0 by Simon Wardley)',
      aliases: ['Wardley map'],
    },
    {
      slug: 'blue-ocean-tools',
      name: 'Blue Ocean tools',
      family: 'strategy-and-opportunity',
      tier: 'V',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'strategy canvas / four actions',
      reasoning: 'IP gate opened (SP9): re-tagged on evidence + distinctness. Vendor evidence (V); documented with attribution, not shipped. Include only with the trademark caveat.',
      branded: true,
      attribution: 'W. Chan Kim & Renee Mauborgne (Blue Ocean Strategy)',
      trademark: 'Blue Ocean Strategy / Strategy Canvas (registered marks of the authors / Blue Ocean Global Network)',
      aliases: ['Strategy Canvas', 'Four Actions Framework', 'ERRC grid'],
    },
    {
      slug: 'porters-five-forces',
      name: "Porter's Five Forces",
      family: 'strategy-and-opportunity',
      tier: 'V',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'competitive-structure scan',
      reasoning: 'Flag and pm-domain. Documented with attribution; include only with caveat.',
      branded: true,
      attribution: 'Michael E. Porter (Harvard Business School)',
      trademark: "Porter's Five Forces (associated with Michael E. Porter / Harvard Business School)",
      aliases: ['Five Forces', '5 Forces'],
    },
    {
      slug: 'swot',
      name: 'SWOT',
      family: 'strategy-and-opportunity',
      tier: 'X',
      status: 'excl',
      verdict: 'reject',
      oneLine: 'strengths / weaknesses / opportunities / threats',
      reasoning: 'Excluded on the merits: weak / contradictory evidence (Hill & Westbrook 1997). Legacy reference only.',
      aliases: ['SWOT analysis'],
    },

    // -------------------------------------------------------------------------
    // 9. Synthesis and reasoning clarity
    // -------------------------------------------------------------------------
    {
      slug: 'issue-tree',
      name: 'Issue Trees',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'decompose a question into a MECE tree',
      reasoning: 'Built and validated. Absorbs MECE decomposition (the principle inside the tree).',
      evalCases: 'skills/think-issue-tree/eval/cases.md',
      aliases: ['Issue tree', 'Logic tree'],
    },
    {
      slug: 'affinity-mapping',
      name: 'Affinity Mapping',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'cluster many notes into emergent themes (bottom-up)',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-affinity-mapping/eval/cases.md',
      attribution: 'Jiro Kawakita (KJ method)',
      aliases: ['Affinity diagram', 'KJ method'],
    },
    {
      slug: 'pyramid-principle',
      name: 'Pyramid Principle',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'answer-first governing thought + grouped support',
      reasoning: 'Built and validated as a shipped skill.',
      evalCases: 'skills/think-pyramid-principle/eval/cases.md',
      attribution: 'Barbara Minto (The Pyramid Principle)',
    },
    {
      slug: 'mece-decomposition',
      name: 'MECE decomposition',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'issue-tree',
      oneLine: 'mutually-exclusive, collectively-exhaustive split',
      reasoning: 'Subsumed: the load-bearing principle inside issue-tree.',
      aliases: ['MECE', 'mutually exclusive collectively exhaustive'],
    },
    {
      slug: 'concept-mapping',
      name: 'Concept Mapping',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'M',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'diagram concepts and labeled relationships',
      reasoning: 'Built and validated.',
      evalCases: 'skills/think-concept-mapping/eval/cases.md',
      attribution: 'Joseph Novak (concept mapping)',
      aliases: ['Concept map'],
    },
    {
      slug: 'dialectical-synthesis',
      name: 'Dialectical synthesis',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'C',
      status: 'cand',
      verdict: 'build',
      oneLine: 'hold thesis/antithesis to a stronger synthesis',
      reasoning: 'Clears the bar but lower priority (C-tier, under-tested).',
      aliases: ['thesis-antithesis-synthesis', 'Hegelian dialectic'],
    },
    {
      slug: 'contradiction-tension-mapping',
      name: 'Contradiction / tension mapping',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'C',
      status: 'cand',
      verdict: 'build',
      oneLine: 'surface central tensions rather than smoothing',
      reasoning: 'Clears the bar but lower priority (C-tier, under-tested).',
      aliases: ['Tension mapping', 'Polarity mapping'],
    },
    {
      slug: 'insight-statement-generation',
      name: 'Insight statement generation',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'turn observations into sharp transferable insights',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['Insight statements'],
    },
    {
      slug: 'sensemaking-matrix',
      name: 'Sensemaking matrix',
      family: 'synthesis-and-reasoning-clarity',
      tier: 'C',
      status: 'cand',
      verdict: 'build',
      oneLine: 'organize conflicting signals for interpretation',
      reasoning: 'Clears the bar but lower priority (C-tier, under-tested).',
    },

    // -------------------------------------------------------------------------
    // 10. Facilitation and group structures (mostly not first-class agent skills)
    // -------------------------------------------------------------------------
    {
      slug: 'silent-writing-before-discussion',
      name: 'Silent writing before discussion',
      family: 'facilitation-and-group-structures',
      tier: 'M',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'brainwriting',
      oneLine: 'write independently first to prevent anchoring',
      reasoning: 'Subsumed: the mechanism is in brainwriting.',
      aliases: ['Silent writing', 'write-before-talk'],
    },
    {
      slug: 'note-and-vote',
      name: 'Note-and-vote / Decider supervote',
      family: 'facilitation-and-group-structures',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'individual notes, then vote / weighted decider',
      reasoning: 'Candidate; an agent can support capture.',
      attribution: 'Google Ventures design sprint (note-and-vote)',
      aliases: ['Note-and-vote', 'Decider supervote'],
    },
    {
      slug: 'dot-voting',
      name: 'Dot voting',
      family: 'facilitation-and-group-structures',
      tier: 'P',
      status: 'flag',
      verdict: 'reject',
      oneLine: 'allocate limited votes',
      reasoning: 'Flag: herding caveats. Include only with the herding caveat.',
      aliases: ['Dotmocracy', 'Dot democracy'],
    },
    {
      slug: 'scaled-participation-formats',
      name: '1-2-4-All / Round-robin / Lean Coffee / World Cafe / Open Space',
      family: 'facilitation-and-group-structures',
      tier: 'P',
      status: 'excl',
      verdict: 'reject',
      oneLine: 'scaled-participation group formats',
      reasoning: 'Excluded: workshop-reference; the value is human social dynamics an AI cannot reproduce.',
      attribution: 'Liberating Structures (1-2-4-All); World Cafe; Open Space (Harrison Owen); Lean Coffee',
      aliases: ['1-2-4-All', 'Round-robin', 'Lean Coffee', 'World Cafe', 'Open Space'],
    },

    // -------------------------------------------------------------------------
    // 11. Meta-thinking and reflection
    // -------------------------------------------------------------------------
    {
      slug: 'after-action-review',
      name: 'After Action Review',
      family: 'meta-thinking-and-reflection',
      tier: 'S',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'expected vs actual -> why -> sustain/change',
      reasoning: 'Empirical-core member.',
      evalCases: 'skills/think-after-action-review/eval/cases.md',
      attribution: 'US Army (After Action Review)',
      aliases: ['AAR'],
    },
    {
      slug: 'belief-update-routine',
      name: 'Belief-update routine',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'shipped',
      verdict: 'shipped',
      oneLine: 'periodically revisit and update key beliefs vs new evidence',
      reasoning: 'Build approved (2026-06-03 vetting) and shipped as think-belief-update-routine; completes the family’s over-time-belief corner. (Catalog source still tagged [next]; truthed-up to shipped here.)',
      evalCases: 'skills/think-belief-update-routine/eval/cases.md',
      aliases: ['Belief updating', 'Bayesian belief update'],
    },
    {
      slug: 'idea-quality-audit',
      name: 'Idea-quality audit',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'recipe',
      verdict: 'recipe',
      oneLine: 'score and pressure-test a batch of ideas (solo + AI)',
      reasoning: 'Ships as the idea-quality-audit recipe (decision-option-review + red-team-light over a shortlist); no separable standalone mechanism.',
      aliases: ['Idea audit'],
    },
    {
      slug: 'what-so-what-now-what',
      name: 'What / So What / Now What',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'observation -> meaning -> action',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      aliases: ['What-So What-Now What'],
    },
    {
      slug: 'pdca-a3',
      name: 'PDCA / A3',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'plan-do-check-act improvement loop',
      reasoning: 'Candidate; overlaps AAR (consider as AAR variants).',
      attribution: 'Deming / Shewhart (PDCA); Toyota (A3)',
      aliases: ['PDCA', 'A3', 'Plan-Do-Check-Act'],
    },
    {
      slug: 'socratic-self-questioning',
      name: 'Socratic self-questioning',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'cand',
      verdict: 'build',
      oneLine: 'disciplined self-interrogation of a belief',
      reasoning: 'Clears the bar but lower priority (P-tier coverage).',
      attribution: 'Socratic method',
      aliases: ['Socratic questioning'],
    },
    {
      slug: 'retro-formats',
      name: 'Plus/Delta, Start/Stop/Continue, Rose/Thorn/Bud',
      family: 'meta-thinking-and-reflection',
      tier: 'P',
      status: 'fold',
      verdict: 'fold',
      foldInto: 'after-action-review',
      oneLine: 'fast retro formats',
      reasoning: 'Subsumed: retro modes / AAR variants.',
      aliases: ['Plus/Delta', 'Start/Stop/Continue', 'Rose/Thorn/Bud'],
    },
  ],
}
