// tests/gen-recipe-commands.test.mjs
// SPEC-09 phase 1b. The generator's job is to carry the recipe's HANDOFF COMPRESSION into the
// command, because that is the authored value of a recipe: what you carry forward at each step is
// what makes a chain cheaper than running the skills back to back. A generator that emitted a
// tidy "run these N skills" summary would look fine and destroy the point, so most of these tests
// are about what must survive the transform, not about the frontmatter.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderCommand, stepCount } from '../scripts/lib/recipe-command-lib.mjs';
import { isWorkflowFile, workflowName } from '../scripts/lib/workflow-mirror-lib.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const RECIPE = `---
name: think-demo
description: Do the demo thing, then the other demo thing.
steps:
  - think-alpha
  - think-beta
metadata:
  version: 0.1.0
---
<!-- thinking-framework-skills | Apache-2.0 -->
# Recipe: demo (workflow)

A framing paragraph that explains why this pairing is honest.

Run the steps in order, carrying forward only the compressed artifact between them:

1. \`think-alpha\` -> carry the **first thing**.
2. \`think-beta\` (on that) -> carry the **second thing**.

Composite artifact: a demo sheet. Full prose: \`recipes/demo.md\`.
`;

test('the command carries the recipe description verbatim', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /^description: Do the demo thing, then the other demo thing\.$/m);
});

test('maps-to names the workflow, which is what S7 resolves', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /^maps-to: think-demo$/m);
});

test('the step count is derived from the steps array, not guessed', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /2 skills chained in a fixed order/);
});

test('THE HANDOFF LINES SURVIVE - this is the whole point of the generator', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /1\. `think-alpha` -> carry the \*\*first thing\*\*\./);
  assert.match(out, /2\. `think-beta` \(on that\) -> carry the \*\*second thing\*\*\./);
});

test('the framing paragraph survives (some recipes justify their own existence there)', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /A framing paragraph that explains why this pairing is honest\./);
});

test('the composite-artifact line survives, so the user knows what they get', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /Composite artifact: a demo sheet\./);
});

test('the H1 title is dropped (the command has its own opening)', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.ok(!out.includes('# Recipe: demo (workflow)'));
});

test('the output is marked generated, with its source and how to regenerate', () => {
  const out = renderCommand('think-demo', RECIPE);
  assert.match(out, /GENERATED by scripts\/gen-recipe-commands\.mjs from _workflows\/think-demo\.md/);
  assert.match(out, /npm run gen:recipe-commands/);
});

test('$ARGUMENTS is present so the command takes input', () => {
  assert.match(renderCommand('think-demo', RECIPE), /\$ARGUMENTS/);
});

test('rendering is deterministic (byte-identical across runs, or --check is meaningless)', () => {
  assert.equal(renderCommand('think-demo', RECIPE), renderCommand('think-demo', RECIPE));
});

// --- against the real recipes -----------------------------------------------------------------

// Every recipe names what to carry forward once per step. Verified across all nine at the time
// this was written: 3/3, 3/3, 2/2, 2/2, 3/3, 3/3, 3/3, 3/3, 4/4. Counting the phrases rather than
// looking for one arrow is what catches a generator that drops a single step's handoff, which is
// the failure mode that would be easiest to miss by eye.
//
// The phrasing varies deliberately and the pattern has to tolerate it: most recipes write
// "-> carry the **X**", but think-idea-quality-audit writes "-> score the batch ...; carry the
// **top few**". An earlier version of this test required `-> carry` and failed on that recipe.
// The recipe was right and the assertion was wrong.
const CARRY_PHRASE = /carry(?:ing)?\s+(?:forward\s+)?(?:only\s+)?[^\n]*\*\*/g;

test('every real recipe renders, keeping one carry-compression phrase per step', () => {
  const names = readdirSync(resolve(ROOT, '_workflows')).filter(isWorkflowFile).map(workflowName);
  assert.ok(names.length >= 9, `expected at least the nine recipes, saw ${names.length}`);
  for (const name of names) {
    const src = readFileSync(resolve(ROOT, '_workflows', `${name}.md`), 'utf8');
    const out = renderCommand(name, src);
    const steps = stepCount(src.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] || '');

    assert.match(out, /^maps-to: /m, `${name}: missing maps-to`);
    assert.ok(out.includes('$ARGUMENTS'), `${name}: missing $ARGUMENTS`);

    const carried = (out.match(CARRY_PHRASE) || []).length;
    assert.ok(
      carried >= steps && carried > 0,
      `${name}: has ${steps} steps but only ${carried} carry-compression phrase(s) survived. ` +
      "The handoff compression is the recipe's value; a chain without it is just N skills in a row.",
    );

    const desc = out.match(/^description: (.+)$/m);
    assert.ok(desc && desc[1].length > 20, `${name}: description missing or too thin`);
  }
});
