#!/usr/bin/env node
// =============================================================================
// check.mjs - the repo's single CI conformance gate (Standard G2: self-hosting CI).
//
// what-it-is:   the one command a contributor or CI runs to validate the plugin against
//               the agent-skills-toolkit Standard.
// what-it-does: spawns the toolkit's portable structural validators, then fourteen
//               repo-local checks in sequence (see the fifteen-layer list below), and
//               exits non-zero if any layer fails or the tracked warning count regresses.
// why:          this is the ONE command CI and a contributor both run; without a single
//               gate, layers could be skipped or run out of order by hand, letting the
//               exact regressions each layer exists to catch (a stale generated file, a
//               caveat that stopped leading, a dead link, an unbumped changelog) drift
//               back into main unnoticed.
// used-by:      npm run check; .github/workflows/ci.yml
//
// `node scripts/check.mjs` (or `npm run check`) runs fifteen layers:
//   1. the toolkit's portable STRUCTURAL validators (the toolkit is the source of truth;
//      vendoring them here would drift),
//   2. the repo-local static eval-case validator (scripts/eval-cases.mjs, SP1): every
//      skills/*/eval/cases.md must be well-formed and name-safe,
//   3. the registry conformance check (scripts/check-registry.mjs, SP3): frameworks/
//      registry.mjs validates against its schema, its generated views are not stale,
//      its referential / IP / eval-coupling invariants hold, and (SPEC-01) every skill on
//      disk describes its own lifecycle truthfully - shipped implies identity.status active,
//      and both eval stamps at measured-* implies maturity: measured,
//   4. the shared applicator engine-copy drift check (scripts/gen-engine.mjs --check, SP7/SP8):
//      the byte-identical engine.md copy stays in sync, and
//   5. the recipe-command drift check (scripts/gen-recipe-commands.mjs --check, SPEC-09 1b + 3):
//      every commands/<recipe>.md, and each allowlisted recipe's agents/<recipe>.md subagent, is
//      regenerated byte-identically from its _workflows/ source, so a hand-edited recipe command
//      or subagent cannot drift from the chain it claims to run, and
//   6. the AGENTS.md table drift check (scripts/gen-agents.mjs --check): the generated
//      Skills + Recipes tables in the contributor guide stay in sync with the catalog, and
//   7. the README count-consistency check (scripts/check-counts.mjs): the four hand-authored
//      count surfaces in README.md (the badges, the lifecycle map, the catalog table headers,
//      and the project-status table) plus the repo-facing docs (docs/getting-started.md,
//      docs/README.md) match the registry / _workflows / tools, and every
//      shipped skill's metadata.family is a valid skill-family slug, and
//   8. the example-coverage ratchet (scripts/check-example-coverage.mjs): every shipped skill
//      has a worked example (a Showcase appearance or a sample) or is grandfathered in
//      scripts/example-coverage-baseline.txt, so a new skill cannot ship without an example.
//   9. the catalog + llms.txt drift check (scripts/gen-catalog.mjs --check): the generated
//      site/public/{catalog.json,evaluated.json,llms.txt} stay in sync with the registry,
//      the skills, and the recipes, so the machine-readable catalog cannot silently go stale, and
//  10. the contested-lens caveat-first contract check (scripts/check-contested.mjs, v0.11.0):
//      every contested lens (caveatFirst in the registry) leads with its evidence caveat across
//      SKILL.md / TEMPLATE / EXAMPLE / sample / eval-cases per its posture, branded lenses carry
//      the trademark attribution on every surface, and the marker agrees across the registry, the
//      SKILL.md frontmatter, and the skill.meta.yml sidecar.
//  11. the mermaid structural-validity check (scripts/check-mermaid.mjs): every mermaid block
//      in repo docs and committed site content is syntactically valid so a broken diagram cannot
//      silently ship.
//  12. the canonical-link check (scripts/check-canonical-links.mjs): every internal link in
//      the repo docs resolves without redirect hops, so stale paths surface immediately.
//  13. the repo-markdown relative-link check (scripts/check-repo-links.mjs): every relative
//      link in repo-facing markdown resolves to a file or anchor that actually exists.
//  14. the changelog consistency check (scripts/check-changelog.mjs): CHANGELOG.md and
//      RELEASE-NOTES.md agree on the most recent version, preventing a version bump that
//      updates one file but forgets the other, and no version block repeats a Keep a
//      Changelog change type, so PRs that each prepend their own "### Added" cannot
//      accumulate duplicate sections unnoticed.
//  15. the eval-results pairing + shape check (scripts/check-eval-results.mjs): every
//      behavioral-eval scorecard under docs/internal/eval-results/ is committed as a paired
//      .md + .json, and each trigger/output scorecard JSON carries its totals contract, so a
//      dropped sidecar (e.g. the 2026-06-19 contested-output gap) cannot recur.
//
// To reproduce a CI failure locally, clone the public toolkit next to this repo:
//   git clone https://github.com/product-on-purpose/agent-skills-toolkit.git ../agent-skills-toolkit
//   node scripts/check.mjs
//
// CI clones it to ./.agent-skills-toolkit and sets AGENT_SKILLS_TOOLKIT (see
// .github/workflows/ci.yml), so the same command runs unchanged. Toolkit resolution is
// worktree-portable: when run from a linked worktree (cwd under .claude/worktrees/), it also
// probes the MAIN repo root, so a toolkit next to the main checkout is still found.
// =============================================================================

import { spawnSync, execSync } from 'node:child_process';
import {
  parseEvaluatorTotals, COUNT_FILE,
  parseEvaluatorComposition, diffComposition, COMPOSITION_FILE,
} from './lib/warning-count-lib.mjs';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'https://github.com/product-on-purpose/agent-skills-toolkit';
const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..'); // this checkout's root (main or worktree), cwd-independent

// Resolve the MAIN repo root too, so running from a linked worktree still finds a toolkit
// checked out next to (or inside) the main checkout rather than under .claude/worktrees/.
let mainRoot = ROOT;
try {
  const commonDir = execSync('git rev-parse --git-common-dir', { cwd: ROOT, encoding: 'utf8' }).trim();
  if (commonDir) mainRoot = resolve(ROOT, commonDir, '..'); // commonDir is <main>/.git -> parent is <main>
} catch {
  /* not a git checkout, or git unavailable: fall back to ROOT */
}

const candidates = [
  process.env.AGENT_SKILLS_TOOLKIT,
  resolve(ROOT, '.agent-skills-toolkit'),
  resolve(ROOT, '..', 'agent-skills-toolkit'),
  resolve(mainRoot, '.agent-skills-toolkit'),
  resolve(mainRoot, '..', 'agent-skills-toolkit'),
].filter(Boolean);

const toolkit = candidates.find((p) => p && existsSync(resolve(p, 'scripts', 'evaluate.mjs')));
if (!toolkit) {
  console.error(
    'Conformance gate: agent-skills-toolkit (the validators) not found.\n' +
    'Fix it in one command, at the ref CI grades against:\n' +
    '  npm run setup\n' +
    'Or do it by hand (but then you must pin the ref yourself - see .github/workflows/ci.yml):\n' +
    `  git clone ${REPO}.git ../agent-skills-toolkit\n` +
    'Looked in:\n  ' + candidates.join('\n  '),
  );
  process.exit(2);
}

const evaluator = resolve(toolkit, 'scripts', 'evaluate.mjs');
console.log(`Running conformance gate via ${evaluator}\n`);
// Captured rather than inherited so the headline warning count can be READ from the run and
// compared with the committed figure. Output is echoed verbatim, so the console is unchanged.
const structural = spawnSync('node', [evaluator, '.'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
if (structural.stdout) process.stdout.write(structural.stdout);
if (structural.stderr) process.stderr.write(structural.stderr);

// The gate's own warning count, asserted instead of re-typed. check-counts.mjs separately
// proves the published prose matches this same committed number; this half proves the
// committed number still matches a live run. It has drifted three times without either.
const liveTotals = parseEvaluatorTotals(structural.stdout || '') || parseEvaluatorTotals(structural.stderr || '');
const countPath = resolve(ROOT, ...COUNT_FILE.split('/'));
let warningCountProblem = null;
if (!liveTotals) {
  warningCountProblem = 'could not read the evaluator totals line; the warning-count assertion did not run';
} else if (!existsSync(countPath)) {
  warningCountProblem = `${COUNT_FILE} is missing (canonical gate warning count)`;
} else {
  const committed = Number(readFileSync(countPath, 'utf8').trim());
  if (committed !== liveTotals.warnings) {
    warningCountProblem =
      `the run reports ${liveTotals.warnings} warning(s) but ${COUNT_FILE} says ${committed}. ` +
      'Either fix the new warning, or update that file AND the prose surfaces it governs ' +
      '(check-counts.mjs names them).';
  }
}
// The same run also carries the BREAKDOWN, and the breakdown is published beside the total in
// six places. Asserting only the total let the G9 sweep take `39 G9` to zero while every page
// went on naming 39 source-docblock warnings - so the per-requirement tally is asserted too,
// in both directions: a family appearing is drift, and a family DISAPPEARING is drift as well.
const compositionPath = resolve(ROOT, ...COMPOSITION_FILE.split('/'));
if (!warningCountProblem) {
  const live = parseEvaluatorComposition(structural.stdout || '');
  if (!Object.keys(live).length) {
    warningCountProblem = 'could not parse any `[warn] <REQ>:` lines from the run; the composition assertion did not run';
  } else if (!existsSync(compositionPath)) {
    warningCountProblem = `${COMPOSITION_FILE} is missing (canonical warning breakdown)`;
  } else {
    let committedComposition = null;
    try {
      committedComposition = JSON.parse(readFileSync(compositionPath, 'utf8')).byRequirement;
    } catch (err) {
      warningCountProblem = `${COMPOSITION_FILE} is not valid JSON (${err.message})`;
    }
    if (committedComposition) {
      const drift = diffComposition(live, committedComposition);
      const liveSum = Object.values(live).reduce((n, v) => n + v, 0);
      if (liveSum !== liveTotals.warnings) {
        // A mismatch here means the evaluator's own output is internally inconsistent, or the
        // warn-line parser has fallen behind its format. Either way the composition figure
        // cannot be trusted, and saying so beats publishing it.
        drift.push(`the per-requirement tally sums to ${liveSum} but the totals line says ${liveTotals.warnings} warning(s) - the warn-line parser may no longer match the evaluator's format`);
      }
      if (drift.length) {
        warningCountProblem =
          `the warning breakdown does not match ${COMPOSITION_FILE}:\n    - ${drift.join('\n    - ')}\n` +
          '  Update that file AND the prose surfaces it governs (check-counts.mjs names them).';
      }
    }
  }
}

if (warningCountProblem) {
  console.error(`
check: warning-count drift - ${warningCountProblem}`);
} else {
  const live = parseEvaluatorComposition(structural.stdout || '');
  const shape = Object.entries(live).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${v} ${k}`).join(', ');
  console.log(`
check: warning count ${liveTotals.warnings} matches ${COUNT_FILE}, and its composition (${shape}) matches ${COMPOSITION_FILE}.`);
}

console.log('\nRunning static eval-case validator (scripts/eval-cases.mjs)\n');
const evalCases = spawnSync('node', [resolve(ROOT, 'scripts', 'eval-cases.mjs'), ROOT], { stdio: 'inherit' });

console.log('\nRunning registry conformance check (scripts/check-registry.mjs)\n');
const registry = spawnSync('node', [resolve(ROOT, 'scripts', 'check-registry.mjs'), ROOT], { stdio: 'inherit' });

console.log('\nRunning engine-copy drift check (scripts/gen-engine.mjs --check)\n');
const engine = spawnSync('node', [resolve(ROOT, 'scripts', 'gen-engine.mjs'), '--check'], { stdio: 'inherit' });

console.log('\nRunning recipe-command drift check (scripts/gen-recipe-commands.mjs --check)\n');
const recipeCmds = spawnSync('node', [resolve(ROOT, 'scripts', 'gen-recipe-commands.mjs'), '--check'], { stdio: 'inherit' });

console.log('\nRunning AGENTS.md table drift check (scripts/gen-agents.mjs --check)\n');
const agents = spawnSync('node', [resolve(ROOT, 'scripts', 'gen-agents.mjs'), '--check'], { stdio: 'inherit' });

console.log('\nRunning README count-consistency check (scripts/check-counts.mjs)\n');
const counts = spawnSync('node', [resolve(ROOT, 'scripts', 'check-counts.mjs')], { stdio: 'inherit' });

console.log('\nRunning example-coverage ratchet (scripts/check-example-coverage.mjs)\n');
const coverage = spawnSync('node', [resolve(ROOT, 'scripts', 'check-example-coverage.mjs')], { stdio: 'inherit' });

console.log('\nRunning catalog + llms.txt drift check (scripts/gen-catalog.mjs --check)\n');
const catalog = spawnSync('node', [resolve(ROOT, 'scripts', 'gen-catalog.mjs'), '--check'], { stdio: 'inherit' });

console.log('\nRunning contested-lens caveat-first contract check (scripts/check-contested.mjs)\n');
const contested = spawnSync('node', [resolve(ROOT, 'scripts', 'check-contested.mjs'), ROOT], { stdio: 'inherit' });

console.log('\nRunning mermaid structural-validity check (scripts/check-mermaid.mjs)\n');
const mermaid = spawnSync('node', [resolve(ROOT, 'scripts', 'check-mermaid.mjs'), 'README.md', 'AGENTS.md', 'docs', 'site/src/content/docs'], { cwd: ROOT, stdio: 'inherit' });

console.log('\nRunning canonical-link (no redirect-hop) check (scripts/check-canonical-links.mjs)\n');
const canonical = spawnSync('node', [resolve(ROOT, 'scripts', 'check-canonical-links.mjs')], { stdio: 'inherit' });

console.log('\nRunning repo-markdown relative-link check (scripts/check-repo-links.mjs)\n');
const repoLinks = spawnSync('node', [resolve(ROOT, 'scripts', 'check-repo-links.mjs')], { stdio: 'inherit' });

console.log('\nRunning changelog consistency check (scripts/check-changelog.mjs)\n');
const changelog = spawnSync('node', [resolve(ROOT, 'scripts', 'check-changelog.mjs')], { stdio: 'inherit' });

console.log('\nRunning eval-results pairing + shape check (scripts/check-eval-results.mjs)\n');
const evalResults = spawnSync('node', [resolve(ROOT, 'scripts', 'check-eval-results.mjs'), ROOT], { stdio: 'inherit' });

// Fail if any layer failed; all run so contributors see all problems at once.
// warningCountProblem rides with layer 1: it is a property of that same evaluator run.
process.exit((warningCountProblem ? 1 : 0) || (structural.status ?? 1) || (evalCases.status ?? 1) || (registry.status ?? 1) || (engine.status ?? 1) || (recipeCmds.status ?? 1) || (agents.status ?? 1) || (counts.status ?? 1) || (coverage.status ?? 1) || (catalog.status ?? 1) || (contested.status ?? 1) || (mermaid.status ?? 1) || (canonical.status ?? 1) || (repoLinks.status ?? 1) || (changelog.status ?? 1) || (evalResults.status ?? 1));
