#!/usr/bin/env node
// gen-site.mjs - generate the Astro Starlight site content from the skills library.
//
// The site is a GENERATED VIEW: the skills are the source of truth. This reads
// library.json + each skill's SKILL.md / evidence/dossier.md / references/EXAMPLE.md /
// skill.meta.yml + the _workflows recipes, and emits Starlight pages under
// site/src/content/docs/{frameworks,families,recipes,evidence}. Run via `npm run gen`
// (or it runs automatically before `astro build`). Generated pages are gitignored;
// edit the skill and regenerate, never hand-edit the output.
//
// No dependencies. UTF-8 in/out (Windows cp1252 would corrupt otherwise).

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'site', 'src', 'content', 'docs');
const OUT = {
  frameworks: join(DOCS, 'frameworks'),
  families: join(DOCS, 'families'),
  recipes: join(DOCS, 'recipes'),
  evidence: join(DOCS, 'evidence'),
};

// --- helpers ----------------------------------------------------------------
function readFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  let key = null; // current top-level key with an open block (map or list, decided lazily)
  for (const raw of m[1].split(/\r?\n/)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    const line = raw.trim();
    if (line.startsWith('- ')) {
      if (key) { if (!Array.isArray(out[key])) out[key] = []; out[key].push(strip(line.slice(2))); }
      continue;
    }
    const indent = raw.length - raw.replace(/^\s+/, '').length;
    const kv = line.match(/^([A-Za-z0-9_.-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, k, v] = kv;
    if (indent === 0) {
      if (v === '') { key = k; out[k] = out[k] ?? {}; }
      else { key = null; out[k] = strip(v); }
    } else if (key && !Array.isArray(out[key])) {
      if (typeof out[key] !== 'object') out[key] = {};
      out[key][k] = strip(v);
    }
  }
  return out;
}
const strip = (s) => s.replace(/^["']/, '').replace(/["']$/, '').trim();
const bodyOf = (text) => text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
const stripProvenance = (b) => b.replace(/^<!--[\s\S]*?-->\r?\n?/, '');
function splitH1(body) {
  const m = body.match(/^#\s+(.+?)\s*$/m);
  const title = m ? m[1].trim() : null;
  const rest = m ? body.slice(0, m.index) + body.slice(m.index + m[0].length) : body;
  return { title, rest: rest.replace(/^\s+/, '') };
}
function demote(md, by = 2) {
  return md.replace(/^(#{1,6})(\s)/gm, (_, h, s) => '#'.repeat(Math.min(6, h.length + by)) + s);
}
const yaml = (s) => JSON.stringify(typeof s === 'string' ? s : String(s ?? ''));
const BANNER = (extra) => `<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit${extra ? ` (${extra})` : ''}. -->`;
const firstSentence = (s) => (s || '').split(/\.\s/)[0].replace(/\.$/, '') + '.';
function useWhen(desc) {
  const i = (desc || '').search(/Use when/i);
  return i === -1 ? null : 'Use when ' + desc.slice(i + 'Use when'.length).trim();
}
const FAMILY_LABEL = (f) =>
  (f || 'other').split('-').map((w) => (w === 'and' ? 'and' : w[0].toUpperCase() + w.slice(1))).join(' ').replace(/ And /g, ' & ');
function tierBadge(t) {
  if (!t) return '';
  // a compound tier like "S/M" -> badge the dominant (first) letter, show full text
  const lead = t.replace(/[^A-Za-z].*$/, '').toUpperCase();
  return `<span class="tier tier-${lead}">${t}</span>`;
}
function sectionFrom(md, headingRe) {
  const lines = md.split(/\r?\n/);
  const start = lines.findIndex((l) => headingRe.test(l));
  if (start === -1) return null;
  const level = (lines[start].match(/^#+/) || ['#'])[0].length;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const h = lines[i].match(/^(#+)\s/);
    if (h && h[1].length <= level) { end = i; break; }
  }
  return lines.slice(start + 1, end).join('\n').trim();
}
function fresh(dir) { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); }

// --- S3 helpers: lenses, jobs, mermaid --------------------------------------
const inlineArr = (text, key) => {
  const m = (text || '').match(new RegExp(key + ':\\s*\\[([^\\]]*)\\]'));
  return m ? m[1].split(',').map((s) => s.trim()).filter(Boolean) : [];
};
// verb-first "job" for the by-job lens, mapped from family (a routing label, not a new taxonomy)
const JOB_OF = {
  'problem-framing': 'Reframe the problem',
  'divergent-ideation': 'Generate options',
  'perspective-and-multi-lens': 'See it from other angles',
  'systems-and-consequences': 'Trace consequences',
  'assumption-and-belief-challenge': 'Challenge assumptions',
  'reasoning-clarity': 'Clarify the reasoning',
  'decision-and-option-evaluation': 'Decide between options',
  'risk-and-resilience': 'Anticipate what could go wrong',
  'synthesis': 'Synthesize into a message',
  'meta-thinking-and-reflection': 'Reflect and route',
};
const tierLead = (t) => (t || '').replace(/[^A-Za-z].*$/, '').toUpperCase();
const TIER_GROUP = { S: 'Strong evidence', M: 'Moderate evidence', P: 'Practitioner', V: 'Vendor', A: 'Anecdotal', C: 'Conceptual', X: 'Excluded' };
const tierGroup = (t) => TIER_GROUP[tierLead(t)] || 'Other';
const TIER_ORDER = { S: 0, M: 1, P: 2, V: 3, A: 4, C: 5, X: 6 };
const mmId = (s) => 'n' + s.replace(/[^A-Za-z0-9]/g, '');
const mmLabel = (s) => (s || '').replace(/"/g, "'"); // mermaid quoted labels cannot contain a double quote

// --- gather -----------------------------------------------------------------
const lib = JSON.parse(readFileSync(join(ROOT, 'library.json'), 'utf8'));
const skills = [];
for (const c of lib.components.skills) {
  const dir = join(ROOT, dirname(c.path));
  const skillMd = readFileSync(join(ROOT, c.path), 'utf8');
  const fm = readFrontmatter(skillMd);
  const meta = fm.metadata || {};
  const bodyRaw = stripProvenance(bodyOf(skillMd));
  const { title, rest: body } = splitH1(bodyRaw);
  const read = (p) => (existsSync(join(dir, p)) ? readFileSync(join(dir, p), 'utf8') : '');
  const dossier = read('evidence/dossier.md');
  const example = read('references/EXAMPLE.md');
  const sidecar = read('skill.meta.yml');
  const artifact = (sidecar.match(/primary_artifact_type:\s*([^\n#]+)/) || [])[1]?.trim() || '';
  skills.push({
    name: fm.name || c.name,
    title: title || c.name,
    id: meta.id || '',
    family: meta.family || 'other',
    tier: meta['evidence-tier'] || '',
    description: fm.description || '',
    body,
    dossier,
    example,
    artifact,
    contexts: inlineArr(sidecar, 'problem_contexts'),
    modes: inlineArr(sidecar, 'thinking_modes'),
  });
}
skills.sort((a, b) => a.title.localeCompare(b.title));

const recipes = [];
const wfDir = join(ROOT, '_workflows');
if (existsSync(wfDir)) {
  for (const f of readdirSync(wfDir).filter((f) => f.endsWith('.md')).sort()) {
    const text = readFileSync(join(wfDir, f), 'utf8');
    const fm = readFrontmatter(text);
    const slug = (fm.name || f.replace(/\.md$/, '')).replace(/^think-/, '');
    const prosePath = join(ROOT, 'recipes', `${slug}.md`);
    const prose = existsSync(prosePath) ? stripProvenance(bodyOf(readFileSync(prosePath, 'utf8'))) : '';
    recipes.push({ name: fm.name, slug, description: fm.description || '', steps: fm.steps || [], prose });
  }
}

// --- emit: framework pages --------------------------------------------------
for (const d of Object.values(OUT)) fresh(d);
let count = 0;
for (const s of skills) {
  const card = [
    ':::note[Quick facts]',
    `**Mechanism:** ${firstSentence(s.description)}`,
    s.artifact ? `**Produces:** ${s.artifact}` : '',
    `**Evidence:** ${tierBadge(s.tier)}  ·  **Domain:** [${FAMILY_LABEL(s.family)}](../../families/${s.family}/)`,
    useWhen(s.description) ? `**${useWhen(s.description)}**` : '',
    ':::',
  ].filter(Boolean).join('\n\n');

  const deepDive = s.example
    ? `## Deep dive: worked example\n\n<details>\n<summary>A full worked run (the shared Northwind scenario)</summary>\n\n${demote(stripProvenance(bodyOf(s.example)))}\n\n</details>`
    : '';
  const grounding = s.dossier
    ? `## Grounding: the full evidence dossier\n\n<details>\n<summary>What the research does and does not show, with graded sources</summary>\n\n${demote(stripProvenance(bodyOf(s.dossier)))}\n\n</details>`
    : '';

  const page = `---
title: ${yaml(s.title)}
description: ${yaml(firstSentence(s.description))}
generated: true
source: ${s.name}
family: ${yaml(s.family)}
evidence_tier: ${yaml(s.tier)}
skill_id: ${yaml(s.id)}
skill_name: ${yaml(s.name)}
---

<!-- GENERATED from skills/${s.name} by scripts/gen-site.mjs - do not hand-edit. -->

${card}

${s.body.trim()}

${deepDive}

${grounding}
`;
  writeFileSync(join(OUT.frameworks, `${s.name}.md`), page, 'utf8');
  count++;
}

// --- emit: family (domain) pages -------------------------------------------
const INTROS = join(ROOT, 'site', 'intros', 'families');
function loadIntro(fam) {
  const p = join(INTROS, `${fam}.md`);
  if (!existsSync(p)) return null;
  const text = readFileSync(p, 'utf8');
  const fm = readFrontmatter(text);
  return {
    order: Number(fm.order) || 999,
    label: fm.label || null,
    tagline: fm.tagline || null,
    body: stripProvenance(bodyOf(text)).trim(),
  };
}
const byFamily = {};
for (const s of skills) (byFamily[s.family] ||= []).push(s);
const famEntries = Object.entries(byFamily).map(([fam, members]) => ({ fam, members, intro: loadIntro(fam) }));
famEntries.sort((a, b) => (a.intro?.order ?? 999) - (b.intro?.order ?? 999) || a.fam.localeCompare(b.fam));
// canonical display label: the authored intro label wins, else the derived label
const FAM_LABELS = Object.fromEntries(famEntries.map((e) => [e.fam, e.intro?.label || FAMILY_LABEL(e.fam)]));
const labelOf = (fam) => FAM_LABELS[fam] || FAMILY_LABEL(fam);
for (const { fam, members, intro } of famEntries) {
  const label = intro?.label || FAMILY_LABEL(fam);
  const rows = members
    .map((s) => `| [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${firstSentence(s.description)} |`)
    .join('\n');
  const blurb = `The **${label}** domain. ${members.length} framework${members.length === 1 ? '' : 's'} in this family. Each is graded honestly; see [the evidence model](../../start/evidence-model/) for the tiers.`;
  const introBody = intro?.body ? `\n\n${intro.body}` : '';
  const page = `---
title: ${yaml(label)}
description: ${yaml(intro?.tagline || `The ${label} domain: the thinking frameworks in this family and when to reach for them.`)}
generated: true
family: ${yaml(fam)}
sidebar:
  order: ${intro?.order ?? 999}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. Intro woven from site/intros/families/${fam}.md -->

${blurb}${introBody}

| Framework | Evidence | What it does |
|---|---|---|
${rows}

> Not sure which of these fits your situation? The [Framework Advisor](../../frameworks/think-framework-advisor/) will diagnose the job and recommend a minimal sequence.
`;
  writeFileSync(join(OUT.families, `${fam}.md`), page, 'utf8');
}

// --- emit: recipe pages -----------------------------------------------------
const titleOf = Object.fromEntries(skills.map((s) => [s.name, s.title]));
for (const r of recipes) {
  const stepList = r.steps.map((st, i) => `${i + 1}. [\`${st}\`](../../frameworks/${st}/)`).join('\n');
  const flowNodes = r.steps.map((st) => `  ${mmId(st)}["${mmLabel(titleOf[st] || st)}"]`).join('\n');
  const flowEdges = r.steps.map((st) => mmId(st)).join(' --> ');
  const flow = r.steps.length
    ? `## Flow\n\n\`\`\`mermaid\ngraph LR\n${flowNodes}\n  ${flowEdges}\n\`\`\`\n\n*Each step passes a compressed artifact to the next. The numbered list below is the same chain in text.*`
    : '';
  const page = `---
title: ${yaml(r.slug.replace(/-/g, ' ').replace(/^\w/, (c) => c.toUpperCase()))}
description: ${yaml(r.description)}
generated: true
source: ${r.name}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

${r.description}

${flow}

## The chain

${stepList}

${demote(r.prose.replace(/^#\s+.*$/m, '').trim(), 1)}
`;
  writeFileSync(join(OUT.recipes, `${r.slug}.md`), page, 'utf8');
}

// --- emit: index pages ------------------------------------------------------
const fwIndexRows = skills
  .map((s) => `| [${s.title}](./${s.name}/) | ${tierBadge(s.tier)} | ${FAMILY_LABEL(s.family)} | ${firstSentence(s.description)} |`)
  .join('\n');
writeFileSync(
  join(OUT.frameworks, 'index.md'),
  `---
title: All frameworks
description: Every thinking framework in the library, by name, with its evidence tier and domain.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

All ${skills.length} frameworks. Browse by domain under [Domains](../families/), or let the [Framework Advisor](./think-framework-advisor/) pick for your situation.

| Framework | Evidence | Domain | What it does |
|---|---|---|---|
${fwIndexRows}
`,
  'utf8'
);

const famIndexRows = famEntries
  .map(({ fam, members, intro }) => `| [${intro?.label || FAMILY_LABEL(fam)}](./${fam}/) | ${members.length} | ${members.map((s) => s.title).join(', ')} |`)
  .join('\n');
writeFileSync(
  join(OUT.families, 'index.md'),
  `---
title: Domains
description: The families of cognitive operations, from reframing to stress-testing to reflection.
generated: true
sidebar:
  order: 0
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The library is organized into domains - families of related thinking operations.

| Domain | Frameworks | Includes |
|---|---|---|
${famIndexRows}
`,
  'utf8'
);

writeFileSync(
  join(OUT.recipes, 'index.md'),
  `---
title: Recipes
description: Composable chains that solve a recurring job end to end.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

Recipes chain several skills into one end-to-end job, passing a compressed artifact at each step.

${recipes.map((r) => `- **[${r.slug.replace(/-/g, ' ')}](./${r.slug}/)** - ${r.description}`).join('\n')}
`,
  'utf8'
);

// --- emit: bibliography -----------------------------------------------------
const biblio = skills
  .map((s) => {
    const src = s.dossier ? sectionFrom(s.dossier, /^#{1,6}\s+(\d+\.\s+)?Sources\b/i) : null;
    if (!src) return '';
    return `### [${s.title}](../frameworks/${s.name}/)  ${tierBadge(s.tier)}\n\n${demote(src, 1)}`;
  })
  .filter(Boolean)
  .join('\n\n');
writeFileSync(
  join(OUT.evidence, 'bibliography.md'),
  `---
title: Bibliography
description: The graded source list across the library - the honest-grading promise made browsable.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs from each skill's dossier - do not hand-edit. -->

This aggregates the graded sources from every skill's evidence dossier, so any claim in the library can be traced to its grounding. Tiers are explained in [the evidence model](../start/evidence-model/). Where evidence is transferred from human studies (not validated for AI use), the dossier says so.

${biblio}
`,
  'utf8'
);
writeFileSync(
  join(OUT.evidence, 'index.md'),
  `---
title: Evidence
description: How this library grades evidence, and the full graded bibliography.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The honest-grading promise is the product. Start with [the evidence model](../start/evidence-model/) for what the S/M/P/V/A/C/X tiers mean, then the [bibliography](./bibliography/) for the graded sources behind every framework.
`,
  'utf8'
);

// --- emit: explore lenses + map + chooser data ------------------------------
// EXPLORE holds generated lens/map pages PLUS the hand-authored chooser.mdx, so it
// is NOT fresh()ed; we only (over)write the generated files by their fixed names.
const EXPLORE = join(DOCS, 'explore');
mkdirSync(EXPLORE, { recursive: true });
const GENERATED = join(ROOT, 'site', 'src', 'generated');
mkdirSync(GENERATED, { recursive: true });
const EBANNER = '<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->';
const fwTable = (list) =>
  ['| Framework | Evidence | What it does |', '|---|---|---|',
    ...list.map((s) => `| [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${firstSentence(s.description)} |`)].join('\n');

// by-job (verb-first, grouped by family in lifecycle order)
const byJob = famEntries.map(({ fam, members }) =>
  `## ${JOB_OF[fam] || labelOf(fam)}\n\n*Domain: [${labelOf(fam)}](../../families/${fam}/)*\n\n${fwTable(members)}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-job.md'), `---
title: By job
description: The frameworks re-sorted by the thinking job you need done, from reframing to deciding to reflecting.
generated: true
sidebar:
  order: 2
---

${EBANNER}

Start from what you are trying to *do*. Each job below maps to a domain; pick the move that fits, or let the [Framework Advisor](../../frameworks/think-framework-advisor/) choose.

${byJob}
`, 'utf8');

// by-evidence (grouped by tier strength)
const tierGroups = {};
for (const s of skills) (tierGroups[tierGroup(s.tier)] ||= []).push(s);
const groupOrder = ['Strong evidence', 'Moderate evidence', 'Practitioner', 'Vendor', 'Anecdotal', 'Conceptual', 'Other'];
const byEvidence = groupOrder.filter((g) => tierGroups[g]).map((g) =>
  `## ${g}\n\n${fwTable(tierGroups[g].slice().sort((a, b) => (TIER_ORDER[tierLead(a.tier)] - TIER_ORDER[tierLead(b.tier)]) || a.title.localeCompare(b.title)))}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-evidence.md'), `---
title: By evidence
description: The frameworks re-sorted by how strong their evidence is, strongest first - for the skeptic who wants the proven core.
generated: true
sidebar:
  order: 3
---

${EBANNER}

Honesty is the product. This view sorts every framework by its evidence tier so you can start from the strong-evidence core and see exactly what is practitioner-grade. The tiers are explained in [the evidence model](../../start/evidence-model/).

${byEvidence}
`, 'utf8');

// by-artifact (sorted by the deliverable)
const byArtifactRows = skills.slice().filter((s) => s.artifact).sort((a, b) => a.artifact.localeCompare(b.artifact))
  .map((s) => `| \`${s.artifact}\` | [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${labelOf(s.family)} |`).join('\n');
writeFileSync(join(EXPLORE, 'by-artifact.md'), `---
title: By artifact
description: The frameworks re-sorted by the concrete deliverable each one produces, from a risk register to an option matrix.
generated: true
sidebar:
  order: 4
---

${EBANNER}

Every framework ends in a named, reusable artifact. If you know the shape of the output you need, find it here.

| Artifact | Framework | Evidence | Domain |
|---|---|---|---|
${byArtifactRows}
`, 'utf8');

// by-context (grouped by problem_contexts tag, most-common first)
const ctxMap = {};
for (const s of skills) for (const c of s.contexts) (ctxMap[c] ||= []).push(s);
const ctxLabel = (c) => c.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
const byContext = Object.entries(ctxMap).sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
  .map(([c, list]) => `## ${ctxLabel(c)}\n\n${fwTable(list.slice().sort((a, b) => a.title.localeCompare(b.title)))}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-context.md'), `---
title: By situation
description: The frameworks re-sorted by the kind of situation you are in - high stakes, high ambiguity, high conflict, and more.
generated: true
sidebar:
  order: 5
---

${EBANNER}

Match the move to the moment. Each situation below lists the frameworks suited to it. For live, context-aware routing, use the interactive [chooser](./chooser/) or the [Framework Advisor](../../frameworks/think-framework-advisor/).

${byContext}
`, 'utf8');

// map.md - the all-frameworks map + the lifecycle flow, each with a text fallback
const mapSubgraphs = famEntries.map(({ fam, members }) =>
  `  subgraph fam${mmId(fam)}["${mmLabel(labelOf(fam))} (${members.length})"]\n` +
  `    direction LR\n    ` +
  members.map((s) => `${mmId(s.name)}["${mmLabel(s.title)}"]:::tier${tierLead(s.tier) || 'P'}`).join(' ~~~ ') +
  `\n  end`).join('\n');
// invisible links stack the family bands top-to-bottom instead of packing them side by side (which made the map illegible)
const mapChain = famEntries.map(({ fam }) => `fam${mmId(fam)}`).join(' ~~~ ');
const lifecycleFlow = famEntries.map(({ fam }) => `${mmId(fam)}["${mmLabel(labelOf(fam))}"]`).join(' --> ');
const mapTextFallback = famEntries.map(({ fam, members }) =>
  `- **[${labelOf(fam)}](../../families/${fam}/)** (${JOB_OF[fam]}): ${members.map((s) => s.title).join(', ')}`).join('\n');
writeFileSync(join(EXPLORE, 'map.md'), `---
title: The map
description: A visual map of all the frameworks by domain, color-coded by evidence tier, plus the thinking lifecycle that connects the domains.
generated: true
sidebar:
  order: 6
---

${EBANNER}

## All frameworks, by domain

Color shows evidence tier: green = strong, blue = moderate, amber = practitioner.

\`\`\`mermaid
graph TD
${mapSubgraphs}
  ${mapChain}
  classDef tierS fill:#e6f4ea,stroke:#137333,color:#0b3d20;
  classDef tierM fill:#e8f0fe,stroke:#1967d2,color:#10316b;
  classDef tierP fill:#fef7e0,stroke:#b06000,color:#5c3a00;
\`\`\`

The same map in text, by domain:

${mapTextFallback}

## The thinking lifecycle

Domains in the order they tend to fire on a piece of work, from framing to reflection. You rarely run all ten; the [Framework Advisor](../../frameworks/think-framework-advisor/) picks the few that fit.

\`\`\`mermaid
graph TD
  ${lifecycleFlow}
\`\`\`

In text: ${famEntries.map(({ fam }) => labelOf(fam)).join(' -> ')}.
`, 'utf8');

// explore/index.md - the Explore landing
writeFileSync(join(EXPLORE, 'index.md'), `---
title: Explore
description: Find a framework five ways - by job, by evidence, by artifact, by situation, on the map, or with the interactive chooser.
generated: true
sidebar:
  order: 0
---

${EBANNER}

The same ${skills.length} frameworks, sorted by whatever you are thinking in:

- **[The chooser](./chooser/)** - tick what your situation looks like and filter live.
- **[By job](./by-job/)** - start from the thinking job you need done.
- **[By evidence](./by-evidence/)** - strongest-evidence methods first.
- **[By artifact](./by-artifact/)** - start from the deliverable you need.
- **[By situation](./by-context/)** - high stakes, high ambiguity, high conflict, and more.
- **[The map](./map/)** - the whole library at a glance, color-coded by evidence.

Or describe your situation in plain language to the [Framework Advisor](../../frameworks/think-framework-advisor/) and get a prioritized plan.
`, 'utf8');

// chooser data (consumed by src/components/Chooser.astro at build time)
const chooserData = skills.map((s) => ({
  slug: s.name,
  title: s.title,
  tier: s.tier,
  tierLead: tierLead(s.tier) || 'P',
  family: s.family,
  familyLabel: labelOf(s.family),
  job: JOB_OF[s.family] || labelOf(s.family),
  artifact: s.artifact,
  contexts: s.contexts,
  modes: s.modes,
  useWhen: (useWhen(s.description) || '').replace(/^Use when\s*/i, '').replace(/\.$/, ''),
}));
writeFileSync(join(GENERATED, 'frameworks.json'), JSON.stringify(chooserData, null, 2), 'utf8');

// site-meta: version + counts, consumed by the footer component
writeFileSync(join(GENERATED, 'site-meta.json'), JSON.stringify({
  version: lib.version || '0.0.0',
  skillCount: skills.length,
  familyCount: Object.keys(byFamily).length,
  recipeCount: recipes.length,
}, null, 2), 'utf8');

console.log(`Generated ${count} framework pages, ${Object.keys(byFamily).length} domains, ${recipes.length} recipes, 4 lenses + map + chooser data, + indexes & bibliography -> ${DOCS}`);
