#!/usr/bin/env node
// gen-site.mjs - generate the Astro Starlight site content from the skills library.
//
// The site is a GENERATED VIEW: the skills are the source of truth. This reads
// library.json + each skill's SKILL.md / evidence/dossier.md / references/EXAMPLE.md /
// skill.meta.yml + the _workflows recipes, and emits Starlight pages under
// site/src/content/docs/{frameworks,families,recipes,evidence}. Run via `npm run gen`
// (or it runs automatically before `astro build`). Generated pages are gitignored;
// edit the skill and regenerate, never hand-edit the output.
//
// No dependencies. UTF-8 in/out (Windows cp1252 would corrupt otherwise).

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'site', 'src', 'content', 'docs');
const OUT = {
  frameworks: join(DOCS, 'frameworks'),
  families: join(DOCS, 'families'),
  recipes: join(DOCS, 'recipes'),
  evidence: join(DOCS, 'evidence'),
};

// --- helpers ----------------------------------------------------------------
function readFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  let key = null; // current top-level key with an open block (map or list, decided lazily)
  for (const raw of m[1].split(/\r?\n/)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    const line = raw.trim();
    if (line.startsWith('- ')) {
      if (key) { if (!Array.isArray(out[key])) out[key] = []; out[key].push(strip(line.slice(2))); }
      continue;
    }
    const indent = raw.length - raw.replace(/^\s+/, '').length;
    const kv = line.match(/^([A-Za-z0-9_.-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, k, v] = kv;
    if (indent === 0) {
      if (v === '') { key = k; out[k] = out[k] ?? {}; }
      else { key = null; out[k] = strip(v); }
    } else if (key && !Array.isArray(out[key])) {
      if (typeof out[key] !== 'object') out[key] = {};
      out[key][k] = strip(v);
    }
  }
  return out;
}
const strip = (s) => s.replace(/^["']/, '').replace(/["']$/, '').trim();
const bodyOf = (text) => text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
const stripProvenance = (b) => b.replace(/^<!--[\s\S]*?-->\r?\n?/, '');
function splitH1(body) {
  const m = body.match(/^#\s+(.+?)\s*$/m);
  const title = m ? m[1].trim() : null;
  const rest = m ? body.slice(0, m.index) + body.slice(m.index + m[0].length) : body;
  return { title, rest: rest.replace(/^\s+/, '') };
}
function demote(md, by = 2) {
  return md.replace(/^(#{1,6})(\s)/gm, (_, h, s) => '#'.repeat(Math.min(6, h.length + by)) + s);
}
const yaml = (s) => JSON.stringify(typeof s === 'string' ? s : String(s ?? ''));
const BANNER = (extra) => `<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit${extra ? ` (${extra})` : ''}. -->`;
const firstSentence = (s) => (s || '').split(/\.\s/)[0].replace(/\.$/, '') + '.';
function useWhen(desc) {
  const i = (desc || '').search(/Use when/i);
  return i === -1 ? null : 'Use when ' + desc.slice(i + 'Use when'.length).trim();
}
const FAMILY_LABEL = (f) =>
  (f || 'other').split('-').map((w) => (w === 'and' ? 'and' : w[0].toUpperCase() + w.slice(1))).join(' ').replace(/ And /g, ' & ');
function tierBadge(t) {
  if (!t) return '';
  // a compound tier like "S/M" -> badge the dominant (first) letter, show full text
  const lead = t.replace(/[^A-Za-z].*$/, '').toUpperCase();
  return `<span class="tier tier-${lead}">${t}</span>`;
}
function sectionFrom(md, headingRe) {
  const lines = md.split(/\r?\n/);
  const start = lines.findIndex((l) => headingRe.test(l));
  if (start === -1) return null;
  const level = (lines[start].match(/^#+/) || ['#'])[0].length;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const h = lines[i].match(/^(#+)\s/);
    if (h && h[1].length <= level) { end = i; break; }
  }
  return lines.slice(start + 1, end).join('\n').trim();
}
function fresh(dir) { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); }

// --- gather -----------------------------------------------------------------
const lib = JSON.parse(readFileSync(join(ROOT, 'library.json'), 'utf8'));
const skills = [];
for (const c of lib.components.skills) {
  const dir = join(ROOT, dirname(c.path));
  const skillMd = readFileSync(join(ROOT, c.path), 'utf8');
  const fm = readFrontmatter(skillMd);
  const meta = fm.metadata || {};
  const bodyRaw = stripProvenance(bodyOf(skillMd));
  const { title, rest: body } = splitH1(bodyRaw);
  const read = (p) => (existsSync(join(dir, p)) ? readFileSync(join(dir, p), 'utf8') : '');
  const dossier = read('evidence/dossier.md');
  const example = read('references/EXAMPLE.md');
  const sidecar = read('skill.meta.yml');
  const artifact = (sidecar.match(/primary_artifact_type:\s*([^\n#]+)/) || [])[1]?.trim() || '';
  skills.push({
    name: fm.name || c.name,
    title: title || c.name,
    id: meta.id || '',
    family: meta.family || 'other',
    tier: meta['evidence-tier'] || '',
    description: fm.description || '',
    body,
    dossier,
    example,
    artifact,
  });
}
skills.sort((a, b) => a.title.localeCompare(b.title));

const recipes = [];
const wfDir = join(ROOT, '_workflows');
if (existsSync(wfDir)) {
  for (const f of readdirSync(wfDir).filter((f) => f.endsWith('.md')).sort()) {
    const text = readFileSync(join(wfDir, f), 'utf8');
    const fm = readFrontmatter(text);
    const slug = (fm.name || f.replace(/\.md$/, '')).replace(/^think-/, '');
    const prosePath = join(ROOT, 'recipes', `${slug}.md`);
    const prose = existsSync(prosePath) ? stripProvenance(bodyOf(readFileSync(prosePath, 'utf8'))) : '';
    recipes.push({ name: fm.name, slug, description: fm.description || '', steps: fm.steps || [], prose });
  }
}

// --- emit: framework pages --------------------------------------------------
for (const d of Object.values(OUT)) fresh(d);
let count = 0;
for (const s of skills) {
  const card = [
    ':::note[Quick facts]',
    `**Mechanism:** ${firstSentence(s.description)}`,
    s.artifact ? `**Produces:** ${s.artifact}` : '',
    `**Evidence:** ${tierBadge(s.tier)}  ·  **Domain:** [${FAMILY_LABEL(s.family)}](../../families/${s.family}/)`,
    useWhen(s.description) ? `**${useWhen(s.description)}**` : '',
    ':::',
  ].filter(Boolean).join('\n\n');

  const deepDive = s.example
    ? `## Deep dive: worked example\n\n<details>\n<summary>A full worked run (the shared Northwind scenario)</summary>\n\n${demote(stripProvenance(bodyOf(s.example)))}\n\n</details>`
    : '';
  const grounding = s.dossier
    ? `## Grounding: the full evidence dossier\n\n<details>\n<summary>What the research does and does not show, with graded sources</summary>\n\n${demote(stripProvenance(bodyOf(s.dossier)))}\n\n</details>`
    : '';

  const page = `---
title: ${yaml(s.title)}
description: ${yaml(firstSentence(s.description))}
generated: true
source: ${s.name}
family: ${yaml(s.family)}
evidence_tier: ${yaml(s.tier)}
skill_id: ${yaml(s.id)}
skill_name: ${yaml(s.name)}
---

<!-- GENERATED from skills/${s.name} by scripts/gen-site.mjs - do not hand-edit. -->

${card}

${s.body.trim()}

${deepDive}

${grounding}
`;
  writeFileSync(join(OUT.frameworks, `${s.name}.md`), page, 'utf8');
  count++;
}

// --- emit: family (domain) pages -------------------------------------------
const byFamily = {};
for (const s of skills) (byFamily[s.family] ||= []).push(s);
for (const [fam, members] of Object.entries(byFamily).sort()) {
  const rows = members
    .map((s) => `| [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${firstSentence(s.description)} |`)
    .join('\n');
  const page = `---
title: ${yaml(FAMILY_LABEL(fam))}
description: ${yaml(`The ${FAMILY_LABEL(fam)} domain: the thinking frameworks in this family and when to reach for them.`)}
generated: true
family: ${yaml(fam)}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The **${FAMILY_LABEL(fam)}** domain. ${members.length} framework${members.length === 1 ? '' : 's'} in this family. Each is graded honestly; see [the evidence model](../../start/evidence-model/) for the tiers.

| Framework | Evidence | What it does |
|---|---|---|
${rows}

> Not sure which of these fits your situation? The [Framework Advisor](../../frameworks/think-framework-advisor/) will diagnose the job and recommend a minimal sequence.
`;
  writeFileSync(join(OUT.families, `${fam}.md`), page, 'utf8');
}

// --- emit: recipe pages -----------------------------------------------------
for (const r of recipes) {
  const stepList = r.steps.map((st, i) => `${i + 1}. [\`${st}\`](../../frameworks/${st}/)`).join('\n');
  const page = `---
title: ${yaml(r.slug.replace(/-/g, ' ').replace(/^\w/, (c) => c.toUpperCase()))}
description: ${yaml(r.description)}
generated: true
source: ${r.name}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

${r.description}

## The chain

${stepList}

${demote(r.prose.replace(/^#\s+.*$/m, '').trim(), 1)}
`;
  writeFileSync(join(OUT.recipes, `${r.slug}.md`), page, 'utf8');
}

// --- emit: index pages ------------------------------------------------------
const fwIndexRows = skills
  .map((s) => `| [${s.title}](./${s.name}/) | ${tierBadge(s.tier)} | ${FAMILY_LABEL(s.family)} | ${firstSentence(s.description)} |`)
  .join('\n');
writeFileSync(
  join(OUT.frameworks, 'index.md'),
  `---
title: All frameworks
description: Every thinking framework in the library, by name, with its evidence tier and domain.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

All ${skills.length} frameworks. Browse by domain under [Domains](../families/), or let the [Framework Advisor](./think-framework-advisor/) pick for your situation.

| Framework | Evidence | Domain | What it does |
|---|---|---|---|
${fwIndexRows}
`,
  'utf8'
);

const famIndexRows = Object.entries(byFamily)
  .sort()
  .map(([fam, m]) => `| [${FAMILY_LABEL(fam)}](./${fam}/) | ${m.length} | ${m.map((s) => s.title).join(', ')} |`)
  .join('\n');
writeFileSync(
  join(OUT.families, 'index.md'),
  `---
title: Domains
description: The families of cognitive operations, from reframing to stress-testing to reflection.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The library is organized into domains - families of related thinking operations.

| Domain | Frameworks | Includes |
|---|---|---|
${famIndexRows}
`,
  'utf8'
);

writeFileSync(
  join(OUT.recipes, 'index.md'),
  `---
title: Recipes
description: Composable chains that solve a recurring job end to end.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

Recipes chain several skills into one end-to-end job, passing a compressed artifact at each step.

${recipes.map((r) => `- **[${r.slug.replace(/-/g, ' ')}](./${r.slug}/)** - ${r.description}`).join('\n')}
`,
  'utf8'
);

// --- emit: bibliography -----------------------------------------------------
const biblio = skills
  .map((s) => {
    const src = s.dossier ? sectionFrom(s.dossier, /^#{1,6}\s+(\d+\.\s+)?Sources\b/i) : null;
    if (!src) return '';
    return `### [${s.title}](../frameworks/${s.name}/)  ${tierBadge(s.tier)}\n\n${demote(src, 1)}`;
  })
  .filter(Boolean)
  .join('\n\n');
writeFileSync(
  join(OUT.evidence, 'bibliography.md'),
  `---
title: Bibliography
description: The graded source list across the library - the honest-grading promise made browsable.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs from each skill's dossier - do not hand-edit. -->

This aggregates the graded sources from every skill's evidence dossier, so any claim in the library can be traced to its grounding. Tiers are explained in [the evidence model](../start/evidence-model/). Where evidence is transferred from human studies (not validated for AI use), the dossier says so.

${biblio}
`,
  'utf8'
);
writeFileSync(
  join(OUT.evidence, 'index.md'),
  `---
title: Evidence
description: How this library grades evidence, and the full graded bibliography.
generated: true
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The honest-grading promise is the product. Start with [the evidence model](../start/evidence-model/) for what the S/M/P/V/A/C/X tiers mean, then the [bibliography](./bibliography/) for the graded sources behind every framework.
`,
  'utf8'
);

console.log(`Generated ${count} framework pages, ${Object.keys(byFamily).length} domains, ${recipes.length} recipes, + indexes & bibliography -> ${DOCS}`);
