#!/usr/bin/env node
// gen-site.mjs - generate the Astro Starlight site content from the skills library.
//
// The site is a GENERATED VIEW: the skills are the source of truth. This reads
// library.json + each skill's SKILL.md / evidence/dossier.md / references/EXAMPLE.md /
// skill.meta.yml + the _workflows recipes, and emits Starlight pages under
// site/src/content/docs/{frameworks,families,recipes,evidence}. Run via `npm run gen`
// (or it runs automatically before `astro build`). Generated pages are gitignored;
// edit the skill and regenerate, never hand-edit the output.
//
// No dependencies. UTF-8 in/out (Windows cp1252 would corrupt otherwise).

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import registry from '../frameworks/registry.mjs';
import { BASE } from './site-base.mjs';
import { extractReleaseTimeline, transformChangelog } from './lib/changelog-lib.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'site', 'src', 'content', 'docs');
const OUT = {
  frameworks: join(DOCS, 'frameworks'),
  families: join(DOCS, 'families'),
  recipes: join(DOCS, 'recipes'),
  evidence: join(DOCS, 'evidence'),
  library: join(DOCS, 'library'), // SP4: Framework Library dossiers + index (registry-driven)
  tools: join(DOCS, 'tools'), // meta-skills (routers/applicators), not graded frameworks
  changelog: join(DOCS, 'changelog'), // Workstream A: generated from root CHANGELOG.md / RELEASE-NOTES.md
};

// --- helpers ----------------------------------------------------------------
function readFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  let key = null; // current top-level key with an open block (map or list, decided lazily)
  for (const raw of m[1].split(/\r?\n/)) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    const line = raw.trim();
    if (line.startsWith('- ')) {
      if (key) { if (!Array.isArray(out[key])) out[key] = []; out[key].push(strip(line.slice(2))); }
      continue;
    }
    const indent = raw.length - raw.replace(/^\s+/, '').length;
    const kv = line.match(/^([A-Za-z0-9_.-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, k, v] = kv;
    if (indent === 0) {
      if (v === '') { key = k; out[k] = out[k] ?? {}; }
      else { key = null; out[k] = strip(v); }
    } else if (key && !Array.isArray(out[key])) {
      if (typeof out[key] !== 'object') out[key] = {};
      out[key][k] = strip(v);
    }
  }
  return out;
}
const strip = (s) => s.replace(/^["']/, '').replace(/["']$/, '').trim();
const bodyOf = (text) => text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
const stripProvenance = (b) => b.replace(/^<!--[\s\S]*?-->\r?\n?/, '');
function splitH1(body) {
  const m = body.match(/^#\s+(.+?)\s*$/m);
  const title = m ? m[1].trim() : null;
  const rest = m ? body.slice(0, m.index) + body.slice(m.index + m[0].length) : body;
  return { title, rest: rest.replace(/^\s+/, '') };
}
function demote(md, by = 2) {
  return md.replace(/^(#{1,6})(\s)/gm, (_, h, s) => '#'.repeat(Math.min(6, h.length + by)) + s);
}
const yaml = (s) => JSON.stringify(typeof s === 'string' ? s : String(s ?? ''));
const BANNER = (extra) => `<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit${extra ? ` (${extra})` : ''}. -->`;
const firstSentence = (s) => (s || '').split(/\.\s/)[0].replace(/\.$/, '') + '.';
function useWhen(desc) {
  const i = (desc || '').search(/Use when/i);
  return i === -1 ? null : 'Use when ' + desc.slice(i + 'Use when'.length).trim();
}
const FAMILY_LABEL = (f) =>
  (f || 'other').split('-').map((w) => (w === 'and' ? 'and' : w[0].toUpperCase() + w.slice(1))).join(' ').replace(/ And /g, ' & ');
function tierBadge(t) {
  if (!t) return '';
  // a compound tier like "S/M" -> badge the dominant (first) letter, show full text
  const lead = t.replace(/[^A-Za-z].*$/, '').toUpperCase();
  return `<span class="tier tier-${lead}">${t}</span>`;
}
function sectionFrom(md, headingRe) {
  const lines = md.split(/\r?\n/);
  const start = lines.findIndex((l) => headingRe.test(l));
  if (start === -1) return null;
  const level = (lines[start].match(/^#+/) || ['#'])[0].length;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const h = lines[i].match(/^(#+)\s/);
    if (h && h[1].length <= level) { end = i; break; }
  }
  return lines.slice(start + 1, end).join('\n').trim();
}
function fresh(dir) { rmSync(dir, { recursive: true, force: true }); mkdirSync(dir, { recursive: true }); }

// --- S3 helpers: lenses, jobs, mermaid --------------------------------------
const inlineArr = (text, key) => {
  const m = (text || '').match(new RegExp(key + ':\\s*\\[([^\\]]*)\\]'));
  return m ? m[1].split(',').map((s) => s.trim()).filter(Boolean) : [];
};
// verb-first "job" for the by-job lens, mapped from family (a routing label, not a new taxonomy)
const JOB_OF = {
  'problem-framing': 'Reframe the problem',
  'divergent-ideation': 'Generate options',
  'perspective-and-multi-lens': 'See it from other angles',
  'systems-and-consequences': 'Trace consequences',
  'assumption-and-belief-challenge': 'Challenge assumptions',
  'reasoning-clarity': 'Clarify the reasoning',
  'decision-and-option-evaluation': 'Decide between options',
  'risk-and-resilience': 'Anticipate what could go wrong',
  'synthesis': 'Synthesize into a message',
  'meta-thinking-and-reflection': 'Reflect and route',
};
const tierLead = (t) => (t || '').replace(/[^A-Za-z].*$/, '').toUpperCase();
const TIER_GROUP = { S: 'Strong evidence', M: 'Moderate evidence', P: 'Practitioner', V: 'Vendor', A: 'Anecdotal', C: 'Conceptual', X: 'Excluded' };
const tierGroup = (t) => TIER_GROUP[tierLead(t)] || 'Other';
const TIER_ORDER = { S: 0, M: 1, P: 2, V: 3, A: 4, C: 5, X: 6 };
const mmId = (s) => 'n' + s.replace(/[^A-Za-z0-9]/g, '');
const mmLabel = (s) => (s || '').replace(/"/g, "'"); // mermaid quoted labels cannot contain a double quote

// --- gather -----------------------------------------------------------------
const lib = JSON.parse(readFileSync(join(ROOT, 'library.json'), 'utf8'));

// Edit-link source for generated pages (SITE-STANDARD "Generated-page Edit links"): generated
// pages are gitignored, so letting Starlight auto-derive their editUrl yields an on-disk path that
// 404s. A per-framework page points editUrl at its skill's SKILL.md (the true 1:1 source); every
// other generated page is an aggregation/synthesis with no single editable source and sets
// editUrl:false. The edit base is derived from library.json's repository, so no new literal is
// introduced and the base-path single source (clause 14.7) is untouched.
const REPO = (lib.repository || '').replace(/\.git$/, '').replace(/\/+$/, '');
const EDIT_BASE = REPO ? `${REPO}/edit/main/` : null;
const skillEditUrl = (s) => (EDIT_BASE && s.srcPath ? `${EDIT_BASE}${s.srcPath}` : false);

const skills = [];
for (const c of lib.components.skills) {
  const dir = join(ROOT, dirname(c.path));
  const skillMd = readFileSync(join(ROOT, c.path), 'utf8');
  const fm = readFrontmatter(skillMd);
  const meta = fm.metadata || {};
  const bodyRaw = stripProvenance(bodyOf(skillMd));
  const { title, rest: body } = splitH1(bodyRaw);
  const read = (p) => (existsSync(join(dir, p)) ? readFileSync(join(dir, p), 'utf8') : '');
  const dossier = read('evidence/dossier.md');
  const example = read('references/EXAMPLE.md');
  const sidecar = read('skill.meta.yml');
  const artifact = (sidecar.match(/primary_artifact_type:\s*([^\n#]+)/) || [])[1]?.trim() || '';
  // Contested-lens posture marker (v0.11.0): renders a "use with caution" admonition + a
  // contested-lens note, so a famous-but-weak lens never reads as an endorsed skill.
  const caveatFirst = /(^|\n)\s*caveat_first:\s*true\b/.test(sidecar);
  const posture = (sidecar.match(/(^|\n)\s*posture:\s*([^\n#]+)/) || [])[2]?.trim() || '';
  skills.push({
    name: fm.name || c.name,
    srcPath: c.path,
    title: title || c.name,
    id: meta.id || '',
    family: meta.family || 'other',
    tier: meta['evidence-tier'] || '',
    description: fm.description || '',
    body,
    dossier,
    example,
    artifact,
    caveatFirst,
    posture,
    concept: stripProvenance(read('references/CONCEPT.md')).trim(),
    contexts: inlineArr(sidecar, 'problem_contexts'),
    modes: inlineArr(sidecar, 'thinking_modes'),
  });
}
skills.sort((a, b) => a.title.localeCompare(b.title));

// Partition into graded FRAMEWORKS vs meta-skill TOOLS (decision A). A tool is a router/applicator
// that operates over the library (the advisor, the research engine, top3, random-frameworks), not a
// graded thinking method. The discriminator is the registry itself: a skill with no registry entry
// is a tool - the same META_SKILLS exemption check-registry.mjs and gen-recommendable.mjs enforce -
// so there is no third hardcoded list and the registry stays the single source of truth.
const fwSlugs = new Set(registry.frameworks.map((e) => `think-${e.slug}`));
const isTool = (s) => !fwSlugs.has(s.name);
const tools = skills.filter(isTool);
const frameworks = skills.filter((s) => !isTool(s));

const recipes = [];
const wfDir = join(ROOT, '_workflows');
if (existsSync(wfDir)) {
  for (const f of readdirSync(wfDir).filter((f) => f.endsWith('.md')).sort()) {
    const text = readFileSync(join(wfDir, f), 'utf8');
    const fm = readFrontmatter(text);
    const slug = (fm.name || f.replace(/\.md$/, '')).replace(/^think-/, '');
    const prosePath = join(ROOT, 'recipes', `${slug}.md`);
    const prose = existsSync(prosePath) ? stripProvenance(bodyOf(readFileSync(prosePath, 'utf8'))) : '';
    recipes.push({ name: fm.name, slug, description: fm.description || '', steps: fm.steps || [], prose });
  }
}

// --- prep output dirs (fresh), then emit changelog + the framework/family/etc pages ---
for (const d of Object.values(OUT)) fresh(d);

// --- changelog (Workstream A): a generated view of the repo-root SSOT files ---
{
  const blob = 'https://github.com/product-on-purpose/thinking-framework-skills/blob/main/';
  const selfLinks = { whatsNew: `${BASE}/changelog/whats-new/`, full: `${BASE}/changelog/full/` };
  const rn = readFileSync(join(ROOT, 'RELEASE-NOTES.md'), 'utf8');
  const cl = readFileSync(join(ROOT, 'CHANGELOG.md'), 'utf8');
  const src = (file) => `> Source of truth: [\`${file}\`](${blob}${file}). This page is generated from it; edit the source and run \`npm run gen\`.\n\n`;
  writeFileSync(join(OUT.changelog, 'whats-new.md'),
`---
title: "What's new"
description: Curated, per-release highlights for the thinking-framework-skills library.
editUrl: false
---
${BANNER('from RELEASE-NOTES.md')}
${src('RELEASE-NOTES.md')}## Release history

${extractReleaseTimeline(rn)}

${transformChangelog(rn, { selfLinks, repoBlobBase: blob })}`, 'utf8');
  writeFileSync(join(OUT.changelog, 'full.md'),
`---
title: Changelog
description: The full technical changelog (Keep a Changelog) for thinking-framework-skills.
editUrl: false
tableOfContents:
  maxHeadingLevel: 2
---
${BANNER('from CHANGELOG.md')}
${src('CHANGELOG.md')}${transformChangelog(cl, { selfLinks, repoBlobBase: blob })}`, 'utf8');
}

let count = 0;
for (const s of frameworks) {
  const card = [
    ':::note[Quick facts]',
    `**Mechanism:** ${firstSentence(s.description)}`,
    s.artifact ? `**Produces:** ${s.artifact}` : '',
    `**Evidence:** ${tierBadge(s.tier)}${s.caveatFirst ? ' · **Contested lens** (caveat-first, explicit-request-only)' : ''}  ·  **Domain:** [${FAMILY_LABEL(s.family)}](../../families/${s.family}/)`,
    useWhen(s.description) ? `**${useWhen(s.description)}**` : '',
    ':::',
  ].filter(Boolean).join('\n\n');

  // Contested lenses lead with a "use with caution" admonition: a famous-but-weak framework we
  // grade honestly and run caveat-first (or warn-and-redirect), never an endorsed default skill.
  const caution = s.caveatFirst
    ? `:::caution[Use with caution: a contested lens]\nThis is a famous framework the library grades **low** on the evidence. It ships ${s.posture === 'warn_redirect' ? 'as **warn-and-redirect**: it owns the name, leads with the controlled-evidence caveat, and routes you to a better-grounded move rather than reproducing the discredited artifact' : 'as **run-caveat-first**: the deficiency leads, then it still produces the (weak) artifact with the missing discipline added'}. It is explicit-request-only: the advisor will not recommend it for a generic prompt.\n:::`
    : '';

  const deepDive = s.example
    ? `## Deep dive: worked example\n\n<details>\n<summary>A full worked run (the shared Northwind scenario)</summary>\n\n${demote(stripProvenance(bodyOf(s.example)))}\n\n</details>`
    : '';
  const grounding = s.dossier
    ? `## Grounding: the full evidence dossier\n\n<details>\n<summary>What the research does and does not show, with graded sources</summary>\n\n${demote(stripProvenance(bodyOf(s.dossier)))}\n\n</details>`
    : '';

  const page = `---
title: ${yaml(s.title)}
description: ${yaml(firstSentence(s.description))}
generated: true
editUrl: ${JSON.stringify(skillEditUrl(s))}
source: ${s.name}
family: ${yaml(s.family)}
evidence_tier: ${yaml(s.tier)}
skill_id: ${yaml(s.id)}
skill_name: ${yaml(s.name)}
---

<!-- GENERATED from skills/${s.name} by scripts/gen-site.mjs - do not hand-edit. -->

${card}
${caution ? `\n${caution}\n` : ''}
${s.concept ? `\n${s.concept}\n` : ''}
${s.body.trim()}

${deepDive}

${grounding}
`;
  writeFileSync(join(OUT.frameworks, `${s.name}.md`), page, 'utf8');
  count++;
}

// --- emit: tool pages (meta-skills: routers/applicators, NOT graded frameworks) -------------
// A deliberately DIFFERENT template from a framework page: no evidence-tier badge and no domain
// link (a tool is not a graded method in a family), a clear meta-skill note instead, then the
// skill's own body. Any evidence grade a tool carries (e.g. the advisor's routing grade) lives in
// its dossier and is about the tool's own behavior, not a framework grade.
for (const s of tools) {
  const deepDive = s.example
    ? `## Deep dive: worked example\n\n<details>\n<summary>A full worked run</summary>\n\n${demote(stripProvenance(bodyOf(s.example)))}\n\n</details>`
    : '';
  const grounding = s.dossier
    ? `## Grounding: the evidence dossier\n\n<details>\n<summary>What the research does and does not show, with graded sources</summary>\n\n${demote(stripProvenance(bodyOf(s.dossier)))}\n\n</details>`
    : '';
  const page = `---
title: ${yaml(s.title)}
description: ${yaml(firstSentence(s.description))}
generated: true
editUrl: ${JSON.stringify(skillEditUrl(s))}
source: ${s.name}
skill_id: ${yaml(s.id)}
skill_name: ${yaml(s.name)}
---

<!-- GENERATED from skills/${s.name} by scripts/gen-site.mjs - do not hand-edit. -->

:::note[Meta-skill, not a graded framework]
This is a **tool** that operates over the framework library - a router or applicator that helps you choose or apply the graded thinking methods, rather than one of those methods itself. Any evidence grade in its dossier refers to the tool's own behavior, not to a framework. Browse the methods it works over in the [Framework Library](../../library/) or [all frameworks](../../frameworks/).
:::

${s.concept ? `${s.concept}\n\n` : ''}${s.body.trim()}

${deepDive}

${grounding}
`;
  writeFileSync(join(OUT.tools, `${s.name}.md`), page, 'utf8');
}
writeFileSync(join(OUT.tools, 'index.md'), `---
title: Tools
description: Meta-skills that operate over the framework library - routers and applicators that help you choose or apply the graded thinking methods.
generated: true
editUrl: false
sidebar:
  order: 0
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

Tools are **meta-skills that operate over the library** - they route you to the right framework, apply several at once, or research new ones - rather than graded thinking methods themselves. For the methods they work over, see the [Framework Library](../library/) or [all frameworks](../frameworks/).

${tools.map((s) => `- **[${s.title}](./${s.name}/)** - ${firstSentence(s.description)}`).join('\n')}
`, 'utf8');

// --- emit: family (domain) pages -------------------------------------------
const INTROS = join(ROOT, 'site', 'intros', 'families');
function loadIntro(fam) {
  const p = join(INTROS, `${fam}.md`);
  if (!existsSync(p)) return null;
  const text = readFileSync(p, 'utf8');
  const fm = readFrontmatter(text);
  return {
    order: Number(fm.order) || 999,
    label: fm.label || null,
    tagline: fm.tagline || null,
    body: stripProvenance(bodyOf(text)).trim(),
  };
}
const byFamily = {};
for (const s of frameworks) (byFamily[s.family] ||= []).push(s);
const famEntries = Object.entries(byFamily).map(([fam, members]) => ({ fam, members, intro: loadIntro(fam) }));
famEntries.sort((a, b) => (a.intro?.order ?? 999) - (b.intro?.order ?? 999) || a.fam.localeCompare(b.fam));
// canonical display label: the authored intro label wins, else the derived label
const FAM_LABELS = Object.fromEntries(famEntries.map((e) => [e.fam, e.intro?.label || FAMILY_LABEL(e.fam)]));
const labelOf = (fam) => FAM_LABELS[fam] || FAMILY_LABEL(fam);
for (const { fam, members, intro } of famEntries) {
  const label = intro?.label || FAMILY_LABEL(fam);
  const rows = members
    .map((s) => `| [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${firstSentence(s.description)} |`)
    .join('\n');
  const blurb = `The **${label}** domain. ${members.length} framework${members.length === 1 ? '' : 's'} in this family. Each is graded honestly; see [the evidence model](../../start/evidence-model/) for the tiers.`;
  const introBody = intro?.body ? `\n\n${intro.body}` : '';
  const page = `---
title: ${yaml(label)}
description: ${yaml(intro?.tagline || `The ${label} domain: the thinking frameworks in this family and when to reach for them.`)}
generated: true
editUrl: false
family: ${yaml(fam)}
sidebar:
  order: ${intro?.order ?? 999}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. Intro woven from site/intros/families/${fam}.md -->

${blurb}${introBody}

| Framework | Evidence | What it does |
|---|---|---|
${rows}

> Not sure which of these fits your situation? The [Framework Advisor](../../tools/think-framework-advisor/) will diagnose the job and recommend a minimal sequence.
`;
  writeFileSync(join(OUT.families, `${fam}.md`), page, 'utf8');
}

// --- emit: recipe pages -----------------------------------------------------
const titleOf = Object.fromEntries(skills.map((s) => [s.name, s.title]));
for (const r of recipes) {
  const stepList = r.steps.map((st, i) => `${i + 1}. [\`${st}\`](../../frameworks/${st}/)`).join('\n');
  const flowNodes = r.steps.map((st) => `  ${mmId(st)}["${mmLabel(titleOf[st] || st)}"]`).join('\n');
  const flowEdges = r.steps.map((st) => mmId(st)).join(' --> ');
  const flow = r.steps.length
    ? `## Flow\n\n\`\`\`mermaid\ngraph LR\n${flowNodes}\n  ${flowEdges}\n\`\`\`\n\n*Each step passes a compressed artifact to the next. The numbered list below is the same chain in text.*`
    : '';
  const page = `---
title: ${yaml(r.slug.replace(/-/g, ' ').replace(/^\w/, (c) => c.toUpperCase()))}
description: ${yaml(r.description)}
generated: true
editUrl: false
source: ${r.name}
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

${r.description}

${flow}

## The chain

${stepList}

${demote(r.prose.replace(/^#\s+.*$/m, '').trim(), 1)}
`;
  writeFileSync(join(OUT.recipes, `${r.slug}.md`), page, 'utf8');
}

// --- emit: index pages ------------------------------------------------------
const fwIndexRows = frameworks
  .map((s) => `| [${s.title}](./${s.name}/) | ${tierBadge(s.tier)} | ${FAMILY_LABEL(s.family)} | ${firstSentence(s.description)} |`)
  .join('\n');
writeFileSync(
  join(OUT.frameworks, 'index.md'),
  `---
title: All frameworks
description: Every thinking framework in the library, by name, with its evidence tier and domain.
generated: true
editUrl: false
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

All ${frameworks.length} frameworks. Browse by domain under [Domains](../families/), or let the [Framework Advisor](../tools/think-framework-advisor/) pick for your situation.

| Framework | Evidence | Domain | What it does |
|---|---|---|---|
${fwIndexRows}
`,
  'utf8'
);

const famIndexRows = famEntries
  .map(({ fam, members, intro }) => `| [${intro?.label || FAMILY_LABEL(fam)}](./${fam}/) | ${members.length} | ${members.map((s) => s.title).join(', ')} |`)
  .join('\n');
writeFileSync(
  join(OUT.families, 'index.md'),
  `---
title: Domains
description: The families of cognitive operations, from reframing to stress-testing to reflection.
generated: true
editUrl: false
sidebar:
  order: 0
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The library is organized into domains - families of related thinking operations.

| Domain | Frameworks | Includes |
|---|---|---|
${famIndexRows}
`,
  'utf8'
);

writeFileSync(
  join(OUT.recipes, 'index.md'),
  `---
title: Recipes
description: Composable chains that solve a recurring job end to end.
generated: true
editUrl: false
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

Recipes chain several skills into one end-to-end job, passing a compressed artifact at each step.

${recipes.map((r) => `- **[${r.slug.replace(/-/g, ' ')}](./${r.slug}/)** - ${r.description}`).join('\n')}
`,
  'utf8'
);

// --- emit: bibliography -----------------------------------------------------
const biblio = frameworks
  .map((s) => {
    const src = s.dossier ? sectionFrom(s.dossier, /^#{1,6}\s+(\d+\.\s+)?Sources\b/i) : null;
    if (!src) return '';
    return `### [${s.title}](../../frameworks/${s.name}/)  ${tierBadge(s.tier)}\n\n${demote(src, 1)}`;
  })
  .filter(Boolean)
  .join('\n\n');
writeFileSync(
  join(OUT.evidence, 'bibliography.md'),
  `---
title: Bibliography
description: The graded source list across the library - the honest-grading promise made browsable.
generated: true
editUrl: false
---

<!-- GENERATED by scripts/gen-site.mjs from each skill's dossier - do not hand-edit. -->

This aggregates the graded sources from every skill's evidence dossier, so any claim in the library can be traced to its grounding. Tiers are explained in [the evidence model](../../start/evidence-model/). Where evidence is transferred from human studies (not validated for AI use), the dossier says so.

${biblio}
`,
  'utf8'
);
writeFileSync(
  join(OUT.evidence, 'index.md'),
  `---
title: Evidence
description: How this library grades evidence, and the full graded bibliography.
generated: true
editUrl: false
---

<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->

The honest-grading promise is the product. Start with [the evidence model](../start/evidence-model/) for what the S/M/P/V/A/C/X tiers mean, then the [bibliography](./bibliography/) for the graded sources behind every framework.
`,
  'utf8'
);

// --- emit: explore lenses + map + chooser data ------------------------------
// EXPLORE holds generated lens/map pages PLUS the hand-authored chooser.mdx, so it
// is NOT fresh()ed; we only (over)write the generated files by their fixed names.
const EXPLORE = join(DOCS, 'explore');
mkdirSync(EXPLORE, { recursive: true });
const GENERATED = join(ROOT, 'site', 'src', 'generated');
mkdirSync(GENERATED, { recursive: true });
const EBANNER = '<!-- GENERATED by scripts/gen-site.mjs - do not hand-edit. -->';
const fwTable = (list) =>
  ['| Framework | Evidence | What it does |', '|---|---|---|',
    ...list.map((s) => `| [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${firstSentence(s.description)} |`)].join('\n');

// by-job (verb-first, grouped by family in lifecycle order)
const byJob = famEntries.map(({ fam, members }) =>
  `## ${JOB_OF[fam] || labelOf(fam)}\n\n*Domain: [${labelOf(fam)}](../../families/${fam}/)*\n\n${fwTable(members)}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-job.md'), `---
title: By job
description: The frameworks re-sorted by the thinking job you need done, from reframing to deciding to reflecting.
generated: true
editUrl: false
sidebar:
  order: 2
---

${EBANNER}

Start from what you are trying to *do*. Each job below maps to a domain; pick the move that fits, or let the [Framework Advisor](../../tools/think-framework-advisor/) choose.

${byJob}
`, 'utf8');

// by-evidence (grouped by tier strength)
const tierGroups = {};
for (const s of frameworks) (tierGroups[tierGroup(s.tier)] ||= []).push(s);
const groupOrder = ['Strong evidence', 'Moderate evidence', 'Practitioner', 'Vendor', 'Anecdotal', 'Conceptual', 'Other'];
const byEvidence = groupOrder.filter((g) => tierGroups[g]).map((g) =>
  `## ${g}\n\n${fwTable(tierGroups[g].slice().sort((a, b) => (TIER_ORDER[tierLead(a.tier)] - TIER_ORDER[tierLead(b.tier)]) || a.title.localeCompare(b.title)))}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-evidence.md'), `---
title: By evidence
description: The frameworks re-sorted by how strong their evidence is, strongest first - for the skeptic who wants the proven core.
generated: true
editUrl: false
sidebar:
  order: 3
---

${EBANNER}

Honesty is the product. This view sorts every framework by its evidence tier so you can start from the strong-evidence core and see exactly what is practitioner-grade. The tiers are explained in [the evidence model](../../start/evidence-model/).

${byEvidence}
`, 'utf8');

// by-artifact (sorted by the deliverable)
const byArtifactRows = frameworks.slice().filter((s) => s.artifact).sort((a, b) => a.artifact.localeCompare(b.artifact))
  .map((s) => `| \`${s.artifact}\` | [${s.title}](../../frameworks/${s.name}/) | ${tierBadge(s.tier)} | ${labelOf(s.family)} |`).join('\n');
writeFileSync(join(EXPLORE, 'by-artifact.md'), `---
title: By artifact
description: The frameworks re-sorted by the concrete deliverable each one produces, from a risk register to an option matrix.
generated: true
editUrl: false
sidebar:
  order: 4
---

${EBANNER}

Every framework ends in a named, reusable artifact. If you know the shape of the output you need, find it here.

| Artifact | Framework | Evidence | Domain |
|---|---|---|---|
${byArtifactRows}
`, 'utf8');

// by-context (grouped by problem_contexts tag, most-common first)
const ctxMap = {};
for (const s of frameworks) for (const c of s.contexts) (ctxMap[c] ||= []).push(s);
const ctxLabel = (c) => c.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
const byContext = Object.entries(ctxMap).sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
  .map(([c, list]) => `## ${ctxLabel(c)}\n\n${fwTable(list.slice().sort((a, b) => a.title.localeCompare(b.title)))}`).join('\n\n');
writeFileSync(join(EXPLORE, 'by-context.md'), `---
title: By situation
description: The frameworks re-sorted by the kind of situation you are in - high stakes, high ambiguity, high conflict, and more.
generated: true
editUrl: false
sidebar:
  order: 5
---

${EBANNER}

Match the move to the moment. Each situation below lists the frameworks suited to it. For live, context-aware routing, use the interactive [chooser](../chooser/) or the [Framework Advisor](../../tools/think-framework-advisor/).

${byContext}
`, 'utf8');

// map.md - the all-frameworks map + the lifecycle flow, each with a text fallback
const mapSubgraphs = famEntries.map(({ fam, members }) =>
  `  subgraph fam${mmId(fam)}["${mmLabel(labelOf(fam))} (${members.length})"]\n` +
  `    direction LR\n    ` +
  members.map((s) => `${mmId(s.name)}["${mmLabel(s.title)}"]:::tier${tierLead(s.tier) || 'P'}`).join(' ~~~ ') +
  `\n  end`).join('\n');
// invisible links stack the family bands top-to-bottom instead of packing them side by side (which made the map illegible)
const mapChain = famEntries.map(({ fam }) => `fam${mmId(fam)}`).join(' ~~~ ');
const lifecycleFlow = famEntries.map(({ fam }) => `${mmId(fam)}["${mmLabel(labelOf(fam))}"]`).join(' --> ');
const mapTextFallback = famEntries.map(({ fam, members }) =>
  `- **[${labelOf(fam)}](../../families/${fam}/)** (${JOB_OF[fam]}): ${members.map((s) => s.title).join(', ')}`).join('\n');
writeFileSync(join(EXPLORE, 'map.md'), `---
title: The map
description: A visual map of all the frameworks by domain, color-coded by evidence tier, plus the thinking lifecycle that connects the domains.
generated: true
editUrl: false
sidebar:
  order: 6
---

${EBANNER}

## All frameworks, by domain

Color shows evidence tier: green = strong, blue = moderate, amber = practitioner.

\`\`\`mermaid
graph TD
${mapSubgraphs}
  ${mapChain}
  classDef tierS fill:#e6f4ea,stroke:#137333,color:#0b3d20;
  classDef tierM fill:#e8f0fe,stroke:#1967d2,color:#10316b;
  classDef tierP fill:#fef7e0,stroke:#b06000,color:#5c3a00;
\`\`\`

The same map in text, by domain:

${mapTextFallback}

## The thinking lifecycle

Domains in the order they tend to fire on a piece of work, from framing to reflection. You rarely run all twelve; the [Framework Advisor](../../tools/think-framework-advisor/) picks the few that fit.

\`\`\`mermaid
graph TD
  ${lifecycleFlow}
\`\`\`

In text: ${famEntries.map(({ fam }) => labelOf(fam)).join(' -> ')}.
`, 'utf8');

// explore/index.md - the Explore landing
writeFileSync(join(EXPLORE, 'index.md'), `---
title: Explore
description: Find a framework five ways - by job, by evidence, by artifact, by situation, on the map, or with the interactive chooser.
generated: true
editUrl: false
sidebar:
  order: 0
---

${EBANNER}

The same ${frameworks.length} frameworks, sorted by whatever you are thinking in:

- **[The chooser](./chooser/)** - tick what your situation looks like and filter live.
- **[By job](./by-job/)** - start from the thinking job you need done.
- **[By evidence](./by-evidence/)** - strongest-evidence methods first.
- **[By artifact](./by-artifact/)** - start from the deliverable you need.
- **[By situation](./by-context/)** - high stakes, high ambiguity, high conflict, and more.
- **[The map](./map/)** - the whole library at a glance, color-coded by evidence.

Or describe your situation in plain language to the [Framework Advisor](../tools/think-framework-advisor/) and get a prioritized plan.
`, 'utf8');

// chooser data (consumed by src/components/Chooser.astro at build time)
const chooserData = frameworks.map((s) => ({
  slug: s.name,
  title: s.title,
  tier: s.tier,
  tierLead: tierLead(s.tier) || 'P',
  family: s.family,
  familyLabel: labelOf(s.family),
  job: JOB_OF[s.family] || labelOf(s.family),
  artifact: s.artifact,
  contexts: s.contexts,
  modes: s.modes,
  useWhen: (useWhen(s.description) || '').replace(/^Use when\s*/i, '').replace(/\.$/, ''),
}));
writeFileSync(join(GENERATED, 'frameworks.json'), JSON.stringify(chooserData, null, 2), 'utf8');

// site-meta: version + counts, consumed by the footer component
writeFileSync(join(GENERATED, 'site-meta.json'), JSON.stringify({
  version: lib.version || '0.0.0',
  skillCount: frameworks.length,
  familyCount: Object.keys(byFamily).length,
  recipeCount: recipes.length,
}, null, 2), 'utf8');

// --- SP4: Framework Library (per-method dossiers + index, registry-driven) ----
// A library/<slug>/ page is emitted ONLY for an entry whose dossier source exists
// (dossierPath set + on disk). pending/absent entries appear in the index as plain text.
// The status block is generated from the registry and spliced between the dossier's
// STATUS:GENERATED markers, so the committed dossier source never carries a status line.
const libFamName = new Map(registry.families.map((f) => [f.slug, f.name]));
const libBySlug = new Map(registry.frameworks.map((e) => [e.slug, e]));
const libDisplayName = (slug) => libBySlug.get(slug)?.name ?? slug;
const libShipped = new Set(registry.frameworks.filter((e) => e.status === 'shipped').map((e) => e.slug));
// Tier-string fix (decision B): the library badge shows the skill's COMPOUND grade (e.g. "S/M")
// for shipped entries, matching the dossier body and the framework page, instead of the registry's
// single governing tier. The registry tier stays single-letter for sorting/checks; non-shipped
// entries (no backing skill) keep the registry tier - they have no compound grade to diverge from.
const skillCompound = new Map(skills.map((s) => [s.name.replace(/^think-/, ''), s.tier]));
const libGrade = (e) => (libShipped.has(e.slug) && skillCompound.get(e.slug)) || e.tier;
const LIB_STATUS = (st) => ({
  shipped: 'Shipped', fold: 'Folded', cand: 'Candidate', recipe: 'Candidate', next: 'Candidate',
  flag: 'Documented, not shipped', excl: 'Documented, not shipped', pm: 'Documented, not shipped',
}[st] || 'Documented, not shipped');
const STATUS_BEGIN = '<!-- STATUS:GENERATED (gen-site.mjs from frameworks/registry.mjs) - do not edit between these markers -->';
const STATUS_END = '<!-- /STATUS:GENERATED -->';
function spliceStatus(body, block) {
  const i = body.indexOf(STATUS_BEGIN);
  const j = body.indexOf(STATUS_END);
  if (i === -1 || j === -1 || j < i) throw new Error('gen-site: a Framework Library dossier is missing its STATUS:GENERATED markers');
  return body.slice(0, i + STATUS_BEGIN.length) + '\n' + block + '\n' + body.slice(j);
}
const libAuthored = new Set();
for (const e of registry.frameworks) {
  if (!e.dossierPath || e.dossierPath === 'pending' || !existsSync(join(ROOT, e.dossierPath))) continue;
  const raw = readFileSync(join(ROOT, e.dossierPath), 'utf8');
  // Fail loudly on a malformed dossier (e.g. leaked authoring preamble) rather than rendering
  // garbage to a public page: bodyOf only strips frontmatter when the file STARTS with ---.
  if (!/^---\r?\n/.test(raw)) throw new Error(`gen-site: ${e.dossierPath} must start with YAML frontmatter (--- on line 1).`);
  const body = bodyOf(raw);
  const lines = [
    `> **Status:** ${LIB_STATUS(e.status)}  ·  **Evidence:** ${tierBadge(libGrade(e))}  ·  **Family:** ${libFamName.get(e.family) || e.family}  ·  **Verdict:** ${e.verdict} (${e.evalDate || registry.seededDate})`,
  ];
  if (e.status === 'shipped' && libShipped.has(e.slug)) lines.push('>', `> Run it: [\`think-${e.slug}\`](../../frameworks/think-${e.slug}/)`);
  if (e.foldInto && libShipped.has(e.foldInto)) lines.push('>', `> Use instead: [\`${libDisplayName(e.foldInto)}\`](../../frameworks/think-${e.foldInto}/)`);
  if (e.branded && e.trademark) {
    // Avoid a tautology when the trademark string already leads with the brand name
    // (e.g. "Six Thinking Hats (a trademark of ...)"); otherwise use the "X is a trademark of Y" form.
    const tm = e.trademark.startsWith(e.name) ? e.trademark : `${e.name} is a trademark of ${e.trademark}`;
    lines.push('>', `> ${tm}.${e.attribution ? ` ${e.attribution}.` : ''}`);
  }
  const page = `---
title: ${yaml(e.name)}
description: ${yaml(e.oneLine)}
generated: true
editUrl: ${JSON.stringify(EDIT_BASE ? `${EDIT_BASE}${e.dossierPath}` : false)}
slug_id: ${yaml(e.slug)}
status: ${yaml(e.status)}
evidence_tier: ${yaml(libGrade(e))}
---

${BANNER('Framework Library dossier; status block from frameworks/registry.mjs, body from ' + e.dossierPath)}

${spliceStatus(body, lines.join('\n')).trim()}
`;
  writeFileSync(join(OUT.library, `${e.slug}.md`), page, 'utf8');
  libAuthored.add(e.slug);
}
const libRow = (e) => `| ${libAuthored.has(e.slug) ? `[${e.name}](./${e.slug}/)` : e.name} | ${tierBadge(libGrade(e))} | ${LIB_STATUS(e.status)}${libAuthored.has(e.slug) ? '' : ' _(dossier pending)_'} |`;
const libGroups = registry.families.map((f) => {
  const members = registry.frameworks.filter((e) => e.family === f.slug);
  return members.length ? `## ${f.name}\n\n| Framework | Evidence | Status |\n|---|---|---|\n${members.map(libRow).join('\n')}` : '';
}).filter(Boolean).join('\n\n');
writeFileSync(join(OUT.library, 'index.md'), `---
title: Framework Library
description: ${yaml('Every thinking method this library has evaluated, with its honest evidence grade and a long-form dossier.')}
generated: true
editUrl: false
sidebar:
  order: 0
---

${BANNER('Framework Library index from frameworks/registry.mjs')}

Every thinking method this library has evaluated, grouped by family, with its honest evidence grade and verdict. Entries marked _(dossier pending)_ are catalogued but their long-form dossier is not yet written. See [why some methods are documented but not shipped](../about/why-not/) and the full [evidence index](../evidence/).

${libGroups}
`, 'utf8');

console.log(`Generated ${count} framework pages, ${Object.keys(byFamily).length} domains, ${recipes.length} recipes, ${libAuthored.size} library dossiers, 4 lenses + map + chooser data, + indexes & bibliography -> ${DOCS}`);
